
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Mar  4 2026 02:12:14 IST (Mar  3 2026 20:42:14 UTC)

// Verification Directory fv/sync_fifo 

module sync_fifo(clk, rst, wr_en, rd_en, wdata, rdata, full, empty);
  input clk, rst, wr_en, rd_en;
  input [7:0] wdata;
  output [7:0] rdata;
  output full, empty;
  wire clk, rst, wr_en, rd_en;
  wire [7:0] wdata;
  wire [7:0] rdata;
  wire full, empty;
  wire [7:0] \mem[15] ;
  wire [7:0] \mem[0] ;
  wire [7:0] \mem[1] ;
  wire [7:0] \mem[8] ;
  wire [7:0] \mem[4] ;
  wire [7:0] \mem[9] ;
  wire [7:0] \mem[11] ;
  wire [7:0] \mem[10] ;
  wire [7:0] \mem[5] ;
  wire [7:0] \mem[6] ;
  wire [7:0] \mem[3] ;
  wire [7:0] \mem[2] ;
  wire [7:0] \mem[14] ;
  wire [7:0] \mem[12] ;
  wire [7:0] \mem[13] ;
  wire [7:0] \mem[7] ;
  wire [4:0] wr_ptr;
  wire [4:0] rd_ptr;
  wire n_0, n_1, n_2, n_5, n_7, n_8, n_9, n_10;
  wire n_11, n_12, n_13, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_29, n_30, n_31, n_32, n_33, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_94, n_95, n_96;
  wire n_97, n_98, n_99, n_100, n_101, n_102, n_103, n_104;
  wire n_105, n_106, n_107, n_108, n_109, n_110, n_111, n_112;
  wire n_113, n_114, n_115, n_116, n_117, n_118, n_119, n_120;
  wire n_121, n_123, n_124, n_126, n_127, n_128, n_129, n_130;
  wire n_131, n_132, n_133, n_134, n_135, n_136, n_137, n_138;
  wire n_139, n_140, n_142, n_144, n_145, n_146, n_147, n_148;
  wire n_149, n_150, n_151, n_152, n_153, n_154, n_155, n_156;
  wire n_157, n_158, n_159, n_160, n_161, n_162, n_163, n_164;
  wire n_165, n_166, n_167, n_168, n_169, n_170, n_171, n_172;
  wire n_173, n_174, n_175, n_176, n_177, n_178, n_179, n_184;
  wire n_185, n_186, n_188, n_189;
  DFFRHQX4 \rdata_reg[0] (.RN (n_179), .CK (clk), .D (n_174), .Q
       (rdata[0]));
  DFFRHQX4 \rdata_reg[6] (.RN (n_179), .CK (clk), .D (n_178), .Q
       (rdata[6]));
  DFFRHQX4 \rdata_reg[7] (.RN (n_179), .CK (clk), .D (n_176), .Q
       (rdata[7]));
  DFFRHQX4 \rdata_reg[1] (.RN (n_179), .CK (clk), .D (n_175), .Q
       (rdata[1]));
  DFFRHQX4 \rdata_reg[2] (.RN (n_179), .CK (clk), .D (n_173), .Q
       (rdata[2]));
  DFFRHQX4 \rdata_reg[3] (.RN (n_179), .CK (clk), .D (n_177), .Q
       (rdata[3]));
  DFFRHQX4 \rdata_reg[4] (.RN (n_179), .CK (clk), .D (n_171), .Q
       (rdata[4]));
  DFFRHQX4 \rdata_reg[5] (.RN (n_179), .CK (clk), .D (n_172), .Q
       (rdata[5]));
  NAND4X1 g5428__2398(.A (n_94), .B (n_96), .C (n_144), .D (n_162), .Y
       (n_178));
  NAND4X1 g5427__5107(.A (n_65), .B (n_66), .C (n_138), .D (n_165), .Y
       (n_177));
  NAND4X1 g5423__6260(.A (n_90), .B (n_91), .C (n_139), .D (n_170), .Y
       (n_176));
  NAND4X1 g5424__4319(.A (n_119), .B (n_82), .C (n_137), .D (n_167), .Y
       (n_175));
  NAND4X1 g5422__8428(.A (n_76), .B (n_77), .C (n_161), .D (n_169), .Y
       (n_174));
  NAND4X1 g5421__5526(.A (n_105), .B (n_70), .C (n_145), .D (n_166), .Y
       (n_173));
  NAND4X1 g5425__6783(.A (n_58), .B (n_99), .C (n_142), .D (n_163), .Y
       (n_172));
  NAND4X1 g5426__3680(.A (n_61), .B (n_78), .C (n_140), .D (n_164), .Y
       (n_171));
  AOI21XL g5431__1617(.A0 (\mem[15] [7]), .A1 (n_168), .B0 (n_157), .Y
       (n_170));
  AOI21XL g5430__2802(.A0 (\mem[15] [0]), .A1 (n_168), .B0 (n_160), .Y
       (n_169));
  AOI21XL g5429__1705(.A0 (\mem[15] [1]), .A1 (n_168), .B0 (n_159), .Y
       (n_167));
  AOI21XL g5432__5122(.A0 (\mem[15] [2]), .A1 (n_168), .B0 (n_158), .Y
       (n_166));
  AOI21XL g5435__8246(.A0 (\mem[15] [3]), .A1 (n_168), .B0 (n_153), .Y
       (n_165));
  AOI21XL g5434__7098(.A0 (\mem[15] [4]), .A1 (n_168), .B0 (n_156), .Y
       (n_164));
  AOI21XL g5433__6131(.A0 (\mem[15] [5]), .A1 (n_168), .B0 (n_155), .Y
       (n_163));
  AOI21XL g5436__1881(.A0 (\mem[15] [6]), .A1 (n_168), .B0 (n_154), .Y
       (n_162));
  AOI221X1 g5575__5115(.A0 (\mem[0] [0]), .A1 (n_104), .B0 (\mem[1]
       [0]), .B1 (n_188), .C0 (n_118), .Y (n_161));
  NAND4X1 g5498__7482(.A (n_117), .B (n_83), .C (n_116), .D (n_100), .Y
       (n_160));
  NAND4X1 g5499__4733(.A (n_115), .B (n_64), .C (n_114), .D (n_72), .Y
       (n_159));
  NAND4X1 g5500__6161(.A (n_108), .B (n_69), .C (n_111), .D (n_68), .Y
       (n_158));
  NAND4X1 g5501__9315(.A (n_120), .B (n_86), .C (n_124), .D (n_81), .Y
       (n_157));
  NAND4X1 g5502__9945(.A (n_109), .B (n_59), .C (n_112), .D (n_89), .Y
       (n_156));
  NAND4X1 g5503__2883(.A (n_107), .B (n_57), .C (n_106), .D (n_56), .Y
       (n_155));
  NAND4X1 g5504__2346(.A (n_123), .B (n_103), .C (n_127), .D (n_79), .Y
       (n_154));
  NAND4X1 g5497__1666(.A (n_63), .B (n_62), .C (n_110), .D (n_128), .Y
       (n_153));
  SDFFQX1 \mem_reg[8][2] (.CK (clk), .D (wdata[2]), .SE (n_151), .SI
       (\mem[8] [2]), .Q (\mem[8] [2]));
  SDFFQX1 \mem_reg[4][3] (.CK (clk), .D (wdata[3]), .SE (n_152), .SI
       (\mem[4] [3]), .Q (\mem[4] [3]));
  SDFFQX1 \mem_reg[4][6] (.CK (clk), .D (wdata[6]), .SE (n_152), .SI
       (\mem[4] [6]), .Q (\mem[4] [6]));
  SDFFQX1 \mem_reg[4][7] (.CK (clk), .D (wdata[7]), .SE (n_152), .SI
       (\mem[4] [7]), .Q (\mem[4] [7]));
  SDFFQX1 \mem_reg[4][5] (.CK (clk), .D (wdata[5]), .SE (n_152), .SI
       (\mem[4] [5]), .Q (\mem[4] [5]));
  SDFFQX1 \mem_reg[8][1] (.CK (clk), .D (wdata[1]), .SE (n_151), .SI
       (\mem[8] [1]), .Q (\mem[8] [1]));
  SDFFQX1 \mem_reg[8][0] (.CK (clk), .D (wdata[0]), .SE (n_151), .SI
       (\mem[8] [0]), .Q (\mem[8] [0]));
  SDFFQX1 \mem_reg[9][7] (.CK (clk), .D (\mem[9] [7]), .SE (n_149), .SI
       (wdata[7]), .Q (\mem[9] [7]));
  SDFFQX1 \mem_reg[8][3] (.CK (clk), .D (wdata[3]), .SE (n_151), .SI
       (\mem[8] [3]), .Q (\mem[8] [3]));
  SDFFQX1 \mem_reg[8][5] (.CK (clk), .D (wdata[5]), .SE (n_151), .SI
       (\mem[8] [5]), .Q (\mem[8] [5]));
  SDFFQX1 \mem_reg[8][6] (.CK (clk), .D (wdata[6]), .SE (n_151), .SI
       (\mem[8] [6]), .Q (\mem[8] [6]));
  SDFFQX1 \mem_reg[8][4] (.CK (clk), .D (wdata[4]), .SE (n_151), .SI
       (\mem[8] [4]), .Q (\mem[8] [4]));
  SDFFQX1 \mem_reg[8][7] (.CK (clk), .D (wdata[7]), .SE (n_151), .SI
       (\mem[8] [7]), .Q (\mem[8] [7]));
  SDFFQX1 \mem_reg[4][0] (.CK (clk), .D (wdata[0]), .SE (n_152), .SI
       (\mem[4] [0]), .Q (\mem[4] [0]));
  SDFFQX1 \mem_reg[4][1] (.CK (clk), .D (wdata[1]), .SE (n_152), .SI
       (\mem[4] [1]), .Q (\mem[4] [1]));
  SDFFQX1 \mem_reg[11][7] (.CK (clk), .D (\mem[11] [7]), .SE (n_150),
       .SI (wdata[7]), .Q (\mem[11] [7]));
  SDFFQX1 \mem_reg[4][2] (.CK (clk), .D (wdata[2]), .SE (n_152), .SI
       (\mem[4] [2]), .Q (\mem[4] [2]));
  SDFFQX1 \mem_reg[4][4] (.CK (clk), .D (wdata[4]), .SE (n_152), .SI
       (\mem[4] [4]), .Q (\mem[4] [4]));
  SDFFQX1 \mem_reg[10][7] (.CK (clk), .D (\mem[10] [7]), .SE (n_146),
       .SI (wdata[7]), .Q (\mem[10] [7]));
  SDFFQX1 \mem_reg[11][0] (.CK (clk), .D (\mem[11] [0]), .SE (n_150),
       .SI (wdata[0]), .Q (\mem[11] [0]));
  SDFFQX1 \mem_reg[11][1] (.CK (clk), .D (\mem[11] [1]), .SE (n_150),
       .SI (wdata[1]), .Q (\mem[11] [1]));
  SDFFQX1 \mem_reg[11][2] (.CK (clk), .D (\mem[11] [2]), .SE (n_150),
       .SI (wdata[2]), .Q (\mem[11] [2]));
  SDFFQX1 \mem_reg[11][3] (.CK (clk), .D (\mem[11] [3]), .SE (n_150),
       .SI (wdata[3]), .Q (\mem[11] [3]));
  SDFFQX1 \mem_reg[9][2] (.CK (clk), .D (\mem[9] [2]), .SE (n_149), .SI
       (wdata[2]), .Q (\mem[9] [2]));
  SDFFQX1 \mem_reg[5][0] (.CK (clk), .D (\mem[5] [0]), .SE (n_148), .SI
       (wdata[0]), .Q (\mem[5] [0]));
  SDFFQX1 \mem_reg[11][5] (.CK (clk), .D (\mem[11] [5]), .SE (n_150),
       .SI (wdata[5]), .Q (\mem[11] [5]));
  SDFFQX1 \mem_reg[5][1] (.CK (clk), .D (\mem[5] [1]), .SE (n_148), .SI
       (wdata[1]), .Q (\mem[5] [1]));
  SDFFQX1 \mem_reg[11][6] (.CK (clk), .D (\mem[11] [6]), .SE (n_150),
       .SI (wdata[6]), .Q (\mem[11] [6]));
  SDFFQX1 \mem_reg[6][0] (.CK (clk), .D (\mem[6] [0]), .SE (n_147), .SI
       (wdata[0]), .Q (\mem[6] [0]));
  SDFFQX1 \mem_reg[6][1] (.CK (clk), .D (\mem[6] [1]), .SE (n_147), .SI
       (wdata[1]), .Q (\mem[6] [1]));
  SDFFQX1 \mem_reg[6][2] (.CK (clk), .D (\mem[6] [2]), .SE (n_147), .SI
       (wdata[2]), .Q (\mem[6] [2]));
  SDFFQX1 \mem_reg[6][3] (.CK (clk), .D (\mem[6] [3]), .SE (n_147), .SI
       (wdata[3]), .Q (\mem[6] [3]));
  SDFFQX1 \mem_reg[6][4] (.CK (clk), .D (\mem[6] [4]), .SE (n_147), .SI
       (wdata[4]), .Q (\mem[6] [4]));
  SDFFQX1 \mem_reg[6][5] (.CK (clk), .D (\mem[6] [5]), .SE (n_147), .SI
       (wdata[5]), .Q (\mem[6] [5]));
  SDFFQX1 \mem_reg[6][6] (.CK (clk), .D (\mem[6] [6]), .SE (n_147), .SI
       (wdata[6]), .Q (\mem[6] [6]));
  SDFFQX1 \mem_reg[6][7] (.CK (clk), .D (\mem[6] [7]), .SE (n_147), .SI
       (wdata[7]), .Q (\mem[6] [7]));
  SDFFQX1 \mem_reg[5][2] (.CK (clk), .D (\mem[5] [2]), .SE (n_148), .SI
       (wdata[2]), .Q (\mem[5] [2]));
  SDFFQX1 \mem_reg[9][0] (.CK (clk), .D (\mem[9] [0]), .SE (n_149), .SI
       (wdata[0]), .Q (\mem[9] [0]));
  SDFFQX1 \mem_reg[9][1] (.CK (clk), .D (\mem[9] [1]), .SE (n_149), .SI
       (wdata[1]), .Q (\mem[9] [1]));
  SDFFQX1 \mem_reg[11][4] (.CK (clk), .D (\mem[11] [4]), .SE (n_150),
       .SI (wdata[4]), .Q (\mem[11] [4]));
  SDFFQX1 \mem_reg[9][3] (.CK (clk), .D (\mem[9] [3]), .SE (n_149), .SI
       (wdata[3]), .Q (\mem[9] [3]));
  SDFFQX1 \mem_reg[9][4] (.CK (clk), .D (\mem[9] [4]), .SE (n_149), .SI
       (wdata[4]), .Q (\mem[9] [4]));
  SDFFQX1 \mem_reg[9][5] (.CK (clk), .D (\mem[9] [5]), .SE (n_149), .SI
       (wdata[5]), .Q (\mem[9] [5]));
  SDFFQX1 \mem_reg[9][6] (.CK (clk), .D (\mem[9] [6]), .SE (n_149), .SI
       (wdata[6]), .Q (\mem[9] [6]));
  SDFFQX1 \mem_reg[10][0] (.CK (clk), .D (\mem[10] [0]), .SE (n_146),
       .SI (wdata[0]), .Q (\mem[10] [0]));
  SDFFQX1 \mem_reg[10][1] (.CK (clk), .D (\mem[10] [1]), .SE (n_146),
       .SI (wdata[1]), .Q (\mem[10] [1]));
  SDFFQX1 \mem_reg[10][2] (.CK (clk), .D (\mem[10] [2]), .SE (n_146),
       .SI (wdata[2]), .Q (\mem[10] [2]));
  SDFFQX1 \mem_reg[10][4] (.CK (clk), .D (\mem[10] [4]), .SE (n_146),
       .SI (wdata[4]), .Q (\mem[10] [4]));
  SDFFQX1 \mem_reg[10][5] (.CK (clk), .D (\mem[10] [5]), .SE (n_146),
       .SI (wdata[5]), .Q (\mem[10] [5]));
  SDFFQX1 \mem_reg[10][6] (.CK (clk), .D (\mem[10] [6]), .SE (n_146),
       .SI (wdata[6]), .Q (\mem[10] [6]));
  SDFFQX1 \mem_reg[5][3] (.CK (clk), .D (\mem[5] [3]), .SE (n_148), .SI
       (wdata[3]), .Q (\mem[5] [3]));
  SDFFQX1 \mem_reg[5][4] (.CK (clk), .D (\mem[5] [4]), .SE (n_148), .SI
       (wdata[4]), .Q (\mem[5] [4]));
  SDFFQX1 \mem_reg[5][5] (.CK (clk), .D (\mem[5] [5]), .SE (n_148), .SI
       (wdata[5]), .Q (\mem[5] [5]));
  SDFFQX1 \mem_reg[5][7] (.CK (clk), .D (\mem[5] [7]), .SE (n_148), .SI
       (wdata[7]), .Q (\mem[5] [7]));
  SDFFQX1 \mem_reg[10][3] (.CK (clk), .D (\mem[10] [3]), .SE (n_146),
       .SI (wdata[3]), .Q (\mem[10] [3]));
  SDFFQX1 \mem_reg[5][6] (.CK (clk), .D (\mem[5] [6]), .SE (n_148), .SI
       (wdata[6]), .Q (\mem[5] [6]));
  AOI221X1 g5577__7410(.A0 (\mem[4] [2]), .A1 (n_189), .B0 (\mem[3]
       [2]), .B1 (n_92), .C0 (n_71), .Y (n_145));
  AOI221X1 g5571__6417(.A0 (\mem[1] [6]), .A1 (n_188), .B0 (\mem[2]
       [6]), .B1 (n_185), .C0 (n_80), .Y (n_144));
  AOI221X1 g5572__5477(.A0 (\mem[1] [5]), .A1 (n_188), .B0 (\mem[2]
       [5]), .B1 (n_185), .C0 (n_73), .Y (n_142));
  AOI221X1 g5573__2398(.A0 (\mem[1] [4]), .A1 (n_188), .B0 (\mem[2]
       [4]), .B1 (n_185), .C0 (n_60), .Y (n_140));
  AOI221X1 g5574__5107(.A0 (\mem[1] [7]), .A1 (n_188), .B0 (\mem[2]
       [7]), .B1 (n_185), .C0 (n_95), .Y (n_139));
  AOI221X1 g5576__6260(.A0 (\mem[1] [3]), .A1 (n_188), .B0 (\mem[2]
       [3]), .B1 (n_185), .C0 (n_67), .Y (n_138));
  AOI221X1 g5570__4319(.A0 (\mem[5] [1]), .A1 (n_98), .B0 (\mem[6]
       [1]), .B1 (n_97), .C0 (n_102), .Y (n_137));
  SDFFQX1 \mem_reg[14][5] (.CK (clk), .D (\mem[14] [5]), .SE (n_136),
       .SI (wdata[5]), .Q (\mem[14] [5]));
  SDFFQX1 \mem_reg[14][7] (.CK (clk), .D (\mem[14] [7]), .SE (n_136),
       .SI (wdata[7]), .Q (\mem[14] [7]));
  SDFFQX1 \mem_reg[14][0] (.CK (clk), .D (\mem[14] [0]), .SE (n_136),
       .SI (wdata[0]), .Q (\mem[14] [0]));
  SDFFQX1 \mem_reg[0][2] (.CK (clk), .D (wdata[2]), .SE (n_135), .SI
       (\mem[0] [2]), .Q (\mem[0] [2]));
  SDFFQX1 \mem_reg[0][0] (.CK (clk), .D (wdata[0]), .SE (n_135), .SI
       (\mem[0] [0]), .Q (\mem[0] [0]));
  SDFFQX1 \mem_reg[0][3] (.CK (clk), .D (wdata[3]), .SE (n_135), .SI
       (\mem[0] [3]), .Q (\mem[0] [3]));
  SDFFQX1 \mem_reg[0][1] (.CK (clk), .D (wdata[1]), .SE (n_135), .SI
       (\mem[0] [1]), .Q (\mem[0] [1]));
  SDFFQX1 \mem_reg[0][5] (.CK (clk), .D (wdata[5]), .SE (n_135), .SI
       (\mem[0] [5]), .Q (\mem[0] [5]));
  SDFFQX1 \mem_reg[0][7] (.CK (clk), .D (wdata[7]), .SE (n_135), .SI
       (\mem[0] [7]), .Q (\mem[0] [7]));
  SDFFQX1 \mem_reg[12][0] (.CK (clk), .D (wdata[0]), .SE (n_134), .SI
       (\mem[12] [0]), .Q (\mem[12] [0]));
  SDFFQX1 \mem_reg[12][1] (.CK (clk), .D (wdata[1]), .SE (n_134), .SI
       (\mem[12] [1]), .Q (\mem[12] [1]));
  SDFFQX1 \mem_reg[12][2] (.CK (clk), .D (wdata[2]), .SE (n_134), .SI
       (\mem[12] [2]), .Q (\mem[12] [2]));
  SDFFQX1 \mem_reg[12][3] (.CK (clk), .D (wdata[3]), .SE (n_134), .SI
       (\mem[12] [3]), .Q (\mem[12] [3]));
  SDFFQX1 \mem_reg[12][4] (.CK (clk), .D (wdata[4]), .SE (n_134), .SI
       (\mem[12] [4]), .Q (\mem[12] [4]));
  SDFFQX1 \mem_reg[12][5] (.CK (clk), .D (wdata[5]), .SE (n_134), .SI
       (\mem[12] [5]), .Q (\mem[12] [5]));
  SDFFQX1 \mem_reg[12][6] (.CK (clk), .D (wdata[6]), .SE (n_134), .SI
       (\mem[12] [6]), .Q (\mem[12] [6]));
  SDFFQX1 \mem_reg[12][7] (.CK (clk), .D (wdata[7]), .SE (n_134), .SI
       (\mem[12] [7]), .Q (\mem[12] [7]));
  SDFFQX1 \mem_reg[0][6] (.CK (clk), .D (wdata[6]), .SE (n_135), .SI
       (\mem[0] [6]), .Q (\mem[0] [6]));
  SDFFQX1 \mem_reg[0][4] (.CK (clk), .D (wdata[4]), .SE (n_135), .SI
       (\mem[0] [4]), .Q (\mem[0] [4]));
  SDFFQX1 \mem_reg[13][5] (.CK (clk), .D (\mem[13] [5]), .SE (n_133),
       .SI (wdata[5]), .Q (\mem[13] [5]));
  SDFFQX1 \mem_reg[13][3] (.CK (clk), .D (\mem[13] [3]), .SE (n_133),
       .SI (wdata[3]), .Q (\mem[13] [3]));
  SDFFQX1 \mem_reg[1][5] (.CK (clk), .D (wdata[5]), .SE (n_132), .SI
       (\mem[1] [5]), .Q (\mem[1] [5]));
  SDFFQX1 \mem_reg[1][6] (.CK (clk), .D (wdata[6]), .SE (n_132), .SI
       (\mem[1] [6]), .Q (\mem[1] [6]));
  SDFFQX1 \mem_reg[1][7] (.CK (clk), .D (wdata[7]), .SE (n_132), .SI
       (\mem[1] [7]), .Q (\mem[1] [7]));
  SDFFQX1 \mem_reg[1][1] (.CK (clk), .D (wdata[1]), .SE (n_132), .SI
       (\mem[1] [1]), .Q (\mem[1] [1]));
  SDFFQX1 \mem_reg[1][2] (.CK (clk), .D (wdata[2]), .SE (n_132), .SI
       (\mem[1] [2]), .Q (\mem[1] [2]));
  SDFFQX1 \mem_reg[1][4] (.CK (clk), .D (wdata[4]), .SE (n_132), .SI
       (\mem[1] [4]), .Q (\mem[1] [4]));
  SDFFQX1 \mem_reg[2][0] (.CK (clk), .D (wdata[0]), .SE (n_131), .SI
       (\mem[2] [0]), .Q (\mem[2] [0]));
  SDFFQX1 \mem_reg[2][1] (.CK (clk), .D (wdata[1]), .SE (n_131), .SI
       (\mem[2] [1]), .Q (\mem[2] [1]));
  SDFFQX1 \mem_reg[2][2] (.CK (clk), .D (wdata[2]), .SE (n_131), .SI
       (\mem[2] [2]), .Q (\mem[2] [2]));
  SDFFQX1 \mem_reg[2][3] (.CK (clk), .D (wdata[3]), .SE (n_131), .SI
       (\mem[2] [3]), .Q (\mem[2] [3]));
  SDFFQX1 \mem_reg[2][5] (.CK (clk), .D (wdata[5]), .SE (n_131), .SI
       (\mem[2] [5]), .Q (\mem[2] [5]));
  SDFFQX1 \mem_reg[2][6] (.CK (clk), .D (wdata[6]), .SE (n_131), .SI
       (\mem[2] [6]), .Q (\mem[2] [6]));
  SDFFQX1 \mem_reg[2][7] (.CK (clk), .D (wdata[7]), .SE (n_131), .SI
       (\mem[2] [7]), .Q (\mem[2] [7]));
  SDFFQX1 \mem_reg[1][3] (.CK (clk), .D (wdata[3]), .SE (n_132), .SI
       (\mem[1] [3]), .Q (\mem[1] [3]));
  SDFFQX1 \mem_reg[13][2] (.CK (clk), .D (\mem[13] [2]), .SE (n_133),
       .SI (wdata[2]), .Q (\mem[13] [2]));
  SDFFQX1 \mem_reg[13][4] (.CK (clk), .D (\mem[13] [4]), .SE (n_133),
       .SI (wdata[4]), .Q (\mem[13] [4]));
  SDFFQX1 \mem_reg[2][4] (.CK (clk), .D (wdata[4]), .SE (n_131), .SI
       (\mem[2] [4]), .Q (\mem[2] [4]));
  SDFFQX1 \mem_reg[13][6] (.CK (clk), .D (\mem[13] [6]), .SE (n_133),
       .SI (wdata[6]), .Q (\mem[13] [6]));
  SDFFQX1 \mem_reg[13][7] (.CK (clk), .D (\mem[13] [7]), .SE (n_133),
       .SI (wdata[7]), .Q (\mem[13] [7]));
  SDFFQX1 \mem_reg[1][0] (.CK (clk), .D (wdata[0]), .SE (n_132), .SI
       (\mem[1] [0]), .Q (\mem[1] [0]));
  SDFFQX1 \mem_reg[14][3] (.CK (clk), .D (\mem[14] [3]), .SE (n_136),
       .SI (wdata[3]), .Q (\mem[14] [3]));
  SDFFQX1 \mem_reg[14][1] (.CK (clk), .D (\mem[14] [1]), .SE (n_136),
       .SI (wdata[1]), .Q (\mem[14] [1]));
  SDFFQX1 \mem_reg[14][4] (.CK (clk), .D (\mem[14] [4]), .SE (n_136),
       .SI (wdata[4]), .Q (\mem[14] [4]));
  SDFFQX1 \mem_reg[14][2] (.CK (clk), .D (\mem[14] [2]), .SE (n_136),
       .SI (wdata[2]), .Q (\mem[14] [2]));
  SDFFQX1 \mem_reg[14][6] (.CK (clk), .D (\mem[14] [6]), .SE (n_136),
       .SI (wdata[6]), .Q (\mem[14] [6]));
  SDFFQX1 \mem_reg[3][1] (.CK (clk), .D (\mem[3] [1]), .SE (n_130), .SI
       (wdata[1]), .Q (\mem[3] [1]));
  SDFFQX1 \mem_reg[3][2] (.CK (clk), .D (\mem[3] [2]), .SE (n_130), .SI
       (wdata[2]), .Q (\mem[3] [2]));
  SDFFQX1 \mem_reg[3][5] (.CK (clk), .D (\mem[3] [5]), .SE (n_130), .SI
       (wdata[5]), .Q (\mem[3] [5]));
  SDFFQX1 \mem_reg[3][6] (.CK (clk), .D (\mem[3] [6]), .SE (n_130), .SI
       (wdata[6]), .Q (\mem[3] [6]));
  SDFFQX1 \mem_reg[3][7] (.CK (clk), .D (\mem[3] [7]), .SE (n_130), .SI
       (wdata[7]), .Q (\mem[3] [7]));
  SDFFQX1 \mem_reg[3][0] (.CK (clk), .D (\mem[3] [0]), .SE (n_130), .SI
       (wdata[0]), .Q (\mem[3] [0]));
  SDFFQX1 \mem_reg[13][0] (.CK (clk), .D (\mem[13] [0]), .SE (n_133),
       .SI (wdata[0]), .Q (\mem[13] [0]));
  SDFFQX1 \mem_reg[13][1] (.CK (clk), .D (\mem[13] [1]), .SE (n_133),
       .SI (wdata[1]), .Q (\mem[13] [1]));
  SDFFQX1 \mem_reg[3][4] (.CK (clk), .D (\mem[3] [4]), .SE (n_130), .SI
       (wdata[4]), .Q (\mem[3] [4]));
  SDFFQX1 \mem_reg[3][3] (.CK (clk), .D (\mem[3] [3]), .SE (n_130), .SI
       (wdata[3]), .Q (\mem[3] [3]));
  SDFFQX1 \mem_reg[7][2] (.CK (clk), .D (wdata[2]), .SE (n_129), .SI
       (\mem[7] [2]), .Q (\mem[7] [2]));
  SDFFQX1 \mem_reg[7][1] (.CK (clk), .D (wdata[1]), .SE (n_129), .SI
       (\mem[7] [1]), .Q (\mem[7] [1]));
  SDFFQX1 \mem_reg[7][0] (.CK (clk), .D (wdata[0]), .SE (n_129), .SI
       (\mem[7] [0]), .Q (\mem[7] [0]));
  SDFFQX1 \mem_reg[7][3] (.CK (clk), .D (wdata[3]), .SE (n_129), .SI
       (\mem[7] [3]), .Q (\mem[7] [3]));
  SDFFQX1 \mem_reg[7][4] (.CK (clk), .D (wdata[4]), .SE (n_129), .SI
       (\mem[7] [4]), .Q (\mem[7] [4]));
  SDFFQX1 \mem_reg[7][5] (.CK (clk), .D (wdata[5]), .SE (n_129), .SI
       (\mem[7] [5]), .Q (\mem[7] [5]));
  SDFFQX1 \mem_reg[7][7] (.CK (clk), .D (wdata[7]), .SE (n_129), .SI
       (\mem[7] [7]), .Q (\mem[7] [7]));
  SDFFQX1 \mem_reg[7][6] (.CK (clk), .D (wdata[6]), .SE (n_129), .SI
       (\mem[7] [6]), .Q (\mem[7] [6]));
  AOI22X1 g5594__8428(.A0 (\mem[9] [3]), .A1 (n_126), .B0 (\mem[10]
       [3]), .B1 (n_186), .Y (n_128));
  AOI22X1 g5584__5526(.A0 (\mem[9] [6]), .A1 (n_126), .B0 (\mem[10]
       [6]), .B1 (n_186), .Y (n_127));
  AOI22X1 g5591__6783(.A0 (\mem[8] [7]), .A1 (n_184), .B0 (\mem[7]
       [7]), .B1 (n_121), .Y (n_124));
  AOI22X1 g5592__3680(.A0 (\mem[8] [6]), .A1 (n_184), .B0 (\mem[7]
       [6]), .B1 (n_121), .Y (n_123));
  AOI22X1 g5593__1617(.A0 (\mem[9] [7]), .A1 (n_126), .B0 (\mem[10]
       [7]), .B1 (n_186), .Y (n_120));
  AOI22X1 g5583__2802(.A0 (\mem[1] [1]), .A1 (n_188), .B0 (\mem[2]
       [1]), .B1 (n_185), .Y (n_119));
  AO22XL g5601__1705(.A0 (\mem[2] [0]), .A1 (n_185), .B0 (rdata[0]),
       .B1 (n_101), .Y (n_118));
  AOI22X1 g5605__5122(.A0 (\mem[8] [0]), .A1 (n_184), .B0 (\mem[7]
       [0]), .B1 (n_121), .Y (n_117));
  AOI22X1 g5607__8246(.A0 (\mem[9] [0]), .A1 (n_126), .B0 (\mem[10]
       [0]), .B1 (n_186), .Y (n_116));
  AOI22X1 g5612__7098(.A0 (\mem[9] [1]), .A1 (n_126), .B0 (\mem[10]
       [1]), .B1 (n_186), .Y (n_115));
  AOI22X1 g5614__6131(.A0 (\mem[8] [1]), .A1 (n_184), .B0 (\mem[7]
       [1]), .B1 (n_121), .Y (n_114));
  SDFFQX1 \mem_reg[15][7] (.CK (clk), .D (wdata[7]), .SE (n_113), .SI
       (\mem[15] [7]), .Q (\mem[15] [7]));
  SDFFQX1 \mem_reg[15][6] (.CK (clk), .D (wdata[6]), .SE (n_113), .SI
       (\mem[15] [6]), .Q (\mem[15] [6]));
  AOI22X1 g5633__1881(.A0 (\mem[9] [4]), .A1 (n_126), .B0 (\mem[10]
       [4]), .B1 (n_186), .Y (n_112));
  AOI22X1 g5621__5115(.A0 (\mem[9] [2]), .A1 (n_126), .B0 (\mem[10]
       [2]), .B1 (n_186), .Y (n_111));
  AOI22X1 g5628__7482(.A0 (\mem[8] [3]), .A1 (n_184), .B0 (\mem[7]
       [3]), .B1 (n_121), .Y (n_110));
  AOI22X1 g5632__4733(.A0 (\mem[8] [4]), .A1 (n_184), .B0 (\mem[7]
       [4]), .B1 (n_121), .Y (n_109));
  AOI22X1 g5619__6161(.A0 (\mem[8] [2]), .A1 (n_184), .B0 (\mem[7]
       [2]), .B1 (n_121), .Y (n_108));
  AOI22X1 g5637__9315(.A0 (\mem[8] [5]), .A1 (n_184), .B0 (\mem[7]
       [5]), .B1 (n_121), .Y (n_107));
  AOI22X1 g5638__9945(.A0 (\mem[9] [5]), .A1 (n_126), .B0 (\mem[10]
       [5]), .B1 (n_186), .Y (n_106));
  AOI22X1 g5617__2883(.A0 (\mem[0] [2]), .A1 (n_104), .B0 (\mem[2]
       [2]), .B1 (n_185), .Y (n_105));
  SDFFQX1 \mem_reg[15][3] (.CK (clk), .D (wdata[3]), .SE (n_113), .SI
       (\mem[15] [3]), .Q (\mem[15] [3]));
  SDFFQX1 \mem_reg[15][4] (.CK (clk), .D (wdata[4]), .SE (n_113), .SI
       (\mem[15] [4]), .Q (\mem[15] [4]));
  SDFFQX1 \mem_reg[15][0] (.CK (clk), .D (wdata[0]), .SE (n_113), .SI
       (\mem[15] [0]), .Q (\mem[15] [0]));
  SDFFQX1 \mem_reg[15][5] (.CK (clk), .D (wdata[5]), .SE (n_113), .SI
       (\mem[15] [5]), .Q (\mem[15] [5]));
  SDFFQX1 \mem_reg[15][1] (.CK (clk), .D (wdata[1]), .SE (n_113), .SI
       (\mem[15] [1]), .Q (\mem[15] [1]));
  SDFFQX1 \mem_reg[15][2] (.CK (clk), .D (wdata[2]), .SE (n_113), .SI
       (\mem[15] [2]), .Q (\mem[15] [2]));
  AOI22X1 g5595__2346(.A0 (\mem[13] [6]), .A1 (n_85), .B0 (\mem[14]
       [6]), .B1 (n_84), .Y (n_103));
  AO22XL g5608__1666(.A0 (\mem[0] [1]), .A1 (n_104), .B0 (rdata[1]),
       .B1 (n_101), .Y (n_102));
  AOI22X1 g5606__7410(.A0 (\mem[12] [0]), .A1 (n_88), .B0 (\mem[11]
       [0]), .B1 (n_87), .Y (n_100));
  AOI22X1 g5634__6417(.A0 (\mem[5] [5]), .A1 (n_98), .B0 (\mem[6] [5]),
       .B1 (n_97), .Y (n_99));
  AOI22X1 g5582__5477(.A0 (\mem[5] [6]), .A1 (n_98), .B0 (\mem[6] [6]),
       .B1 (n_97), .Y (n_96));
  AO22XL g5585__2398(.A0 (\mem[6] [7]), .A1 (n_97), .B0 (rdata[7]), .B1
       (n_101), .Y (n_95));
  AOI22X1 g5586__5107(.A0 (\mem[4] [6]), .A1 (n_189), .B0 (\mem[3]
       [6]), .B1 (n_92), .Y (n_94));
  AOI22X1 g5587__6260(.A0 (\mem[4] [7]), .A1 (n_189), .B0 (\mem[3]
       [7]), .B1 (n_92), .Y (n_91));
  AOI22X1 g5588__4319(.A0 (\mem[0] [7]), .A1 (n_104), .B0 (\mem[5]
       [7]), .B1 (n_98), .Y (n_90));
  AOI22X1 g5589__8428(.A0 (\mem[12] [4]), .A1 (n_88), .B0 (\mem[11]
       [4]), .B1 (n_87), .Y (n_89));
  AOI22X1 g5590__5526(.A0 (\mem[13] [7]), .A1 (n_85), .B0 (\mem[14]
       [7]), .B1 (n_84), .Y (n_86));
  AOI22X1 g5604__6783(.A0 (\mem[13] [0]), .A1 (n_85), .B0 (\mem[14]
       [0]), .B1 (n_84), .Y (n_83));
  AOI22X1 g5596__3680(.A0 (\mem[4] [1]), .A1 (n_189), .B0 (\mem[3]
       [1]), .B1 (n_92), .Y (n_82));
  AOI22X1 g5597__1617(.A0 (\mem[12] [7]), .A1 (n_88), .B0 (\mem[11]
       [7]), .B1 (n_87), .Y (n_81));
  AO22XL g5598__2802(.A0 (\mem[0] [6]), .A1 (n_104), .B0 (rdata[6]),
       .B1 (n_101), .Y (n_80));
  AOI22X1 g5599__1705(.A0 (\mem[12] [6]), .A1 (n_88), .B0 (\mem[11]
       [6]), .B1 (n_87), .Y (n_79));
  AOI22X1 g5600__5122(.A0 (\mem[5] [4]), .A1 (n_98), .B0 (\mem[6] [4]),
       .B1 (n_97), .Y (n_78));
  AOI22X1 g5602__8246(.A0 (\mem[5] [0]), .A1 (n_98), .B0 (\mem[6] [0]),
       .B1 (n_97), .Y (n_77));
  AOI22X1 g5603__7098(.A0 (\mem[4] [0]), .A1 (n_189), .B0 (\mem[3]
       [0]), .B1 (n_92), .Y (n_76));
  NOR2X2 g5655__6131(.A (n_74), .B (n_75), .Y (n_148));
  NOR2X2 g5661__1881(.A (n_55), .B (n_75), .Y (n_149));
  NAND2BX2 g5656__5115(.AN (n_74), .B (n_53), .Y (n_152));
  AO22XL g5627__7482(.A0 (\mem[0] [5]), .A1 (n_104), .B0 (rdata[5]),
       .B1 (n_101), .Y (n_73));
  AOI22X1 g5613__4733(.A0 (\mem[12] [1]), .A1 (n_88), .B0 (\mem[11]
       [1]), .B1 (n_87), .Y (n_72));
  AO22XL g5615__6161(.A0 (\mem[1] [2]), .A1 (n_188), .B0 (rdata[2]),
       .B1 (n_101), .Y (n_71));
  AOI22X1 g5616__9315(.A0 (\mem[5] [2]), .A1 (n_98), .B0 (\mem[6] [2]),
       .B1 (n_97), .Y (n_70));
  AOI22X1 g5618__9945(.A0 (\mem[13] [2]), .A1 (n_85), .B0 (\mem[14]
       [2]), .B1 (n_84), .Y (n_69));
  AOI22X1 g5620__2883(.A0 (\mem[12] [2]), .A1 (n_88), .B0 (\mem[11]
       [2]), .B1 (n_87), .Y (n_68));
  AO22XL g5622__2346(.A0 (\mem[0] [3]), .A1 (n_104), .B0 (rdata[3]),
       .B1 (n_101), .Y (n_67));
  AOI22X1 g5623__1666(.A0 (\mem[5] [3]), .A1 (n_98), .B0 (\mem[6] [3]),
       .B1 (n_97), .Y (n_66));
  AOI22X1 g5624__7410(.A0 (\mem[4] [3]), .A1 (n_189), .B0 (\mem[3]
       [3]), .B1 (n_92), .Y (n_65));
  AOI22X1 g5625__6417(.A0 (\mem[13] [1]), .A1 (n_85), .B0 (\mem[14]
       [1]), .B1 (n_84), .Y (n_64));
  AOI22X1 g5626__5477(.A0 (\mem[12] [3]), .A1 (n_88), .B0 (\mem[11]
       [3]), .B1 (n_87), .Y (n_63));
  AOI22X1 g5611__2398(.A0 (\mem[13] [3]), .A1 (n_85), .B0 (\mem[14]
       [3]), .B1 (n_84), .Y (n_62));
  AOI22X1 g5630__5107(.A0 (\mem[4] [4]), .A1 (n_189), .B0 (\mem[3]
       [4]), .B1 (n_92), .Y (n_61));
  AO22XL g5629__6260(.A0 (\mem[0] [4]), .A1 (n_104), .B0 (rdata[4]),
       .B1 (n_101), .Y (n_60));
  AOI22X1 g5631__4319(.A0 (\mem[13] [4]), .A1 (n_85), .B0 (\mem[14]
       [4]), .B1 (n_84), .Y (n_59));
  AOI22X1 g5635__8428(.A0 (\mem[4] [5]), .A1 (n_189), .B0 (\mem[3]
       [5]), .B1 (n_92), .Y (n_58));
  AOI22X1 g5636__5526(.A0 (\mem[13] [5]), .A1 (n_85), .B0 (\mem[14]
       [5]), .B1 (n_84), .Y (n_57));
  AOI22X1 g5639__6783(.A0 (\mem[12] [5]), .A1 (n_88), .B0 (\mem[11]
       [5]), .B1 (n_87), .Y (n_56));
  NOR2X2 g5653__3680(.A (n_55), .B (n_54), .Y (n_146));
  NOR2X2 g5652__1617(.A (n_74), .B (n_54), .Y (n_147));
  NOR2X2 g5650__2802(.A (n_55), .B (n_51), .Y (n_150));
  NAND2BX2 g5648__1705(.AN (n_55), .B (n_53), .Y (n_151));
  AND2X1 g5654__5122(.A (n_52), .B (n_48), .Y (n_136));
  AND2X1 g5657__8246(.A (n_52), .B (n_49), .Y (n_133));
  NOR2BX2 g5658__7098(.AN (n_50), .B (n_51), .Y (n_130));
  NAND2X2 g5647__6131(.A (n_52), .B (n_53), .Y (n_134));
  NAND2X2 g5660__1881(.A (n_50), .B (n_49), .Y (n_132));
  NAND2X2 g5659__5115(.A (n_50), .B (n_48), .Y (n_131));
  NAND2X2 g5649__7482(.A (n_50), .B (n_53), .Y (n_135));
  NAND3BX1 g5674__9945(.AN (wr_ptr[3]), .B (n_45), .C (wr_ptr[2]), .Y
       (n_74));
  OR3X1 g5676__2883(.A (n_46), .B (wr_ptr[2]), .C (n_41), .Y (n_55));
  OR3X1 g5683__2346(.A (n_46), .B (wr_ptr[3]), .C (n_12), .Y (n_129));
  AND3XL g5673__1666(.A (n_45), .B (wr_ptr[3]), .C (wr_ptr[2]), .Y
       (n_52));
  NOR2X1 g5671__7410(.A (n_37), .B (n_43), .Y (n_87));
  NOR2X1 g5668__6417(.A (n_44), .B (n_39), .Y (n_121));
  NOR2X1 g5669__5477(.A (n_44), .B (n_38), .Y (n_85));
  NOR2X1 g5670__2398(.A (n_40), .B (n_43), .Y (n_84));
  AND2X1 g5664__5107(.A (n_15), .B (n_42), .Y (n_98));
  NAND2X2 g5672__6260(.A (n_45), .B (n_23), .Y (n_113));
  NOR2X1 g5662__4319(.A (n_44), .B (n_43), .Y (n_168));
  AND2X1 g5663__8428(.A (n_47), .B (n_42), .Y (n_104));
  AND3XL g5675__5526(.A (n_45), .B (n_41), .C (n_17), .Y (n_50));
  SDFFRHQX1 \wr_ptr_reg[0] (.RN (n_179), .CK (clk), .D (n_30), .SE
       (wr_ptr[0]), .SI (n_33), .Q (wr_ptr[0]));
  NOR2X1 g5681__3680(.A (n_40), .B (n_39), .Y (n_97));
  NOR2X1 g5682__1617(.A (n_40), .B (n_38), .Y (n_88));
  NOR2X1 g5677__2802(.A (n_37), .B (n_39), .Y (n_92));
  NOR2X1 g5679__5122(.A (n_37), .B (n_38), .Y (n_126));
  INVX1 g5685(.A (n_45), .Y (n_46));
  SDFFRHQX1 \wr_ptr_reg[1] (.RN (n_179), .CK (clk), .D (n_8), .SE
       (n_33), .SI (wr_ptr[1]), .Q (wr_ptr[1]));
  SDFFRHQX1 \rd_ptr_reg[4] (.RN (n_179), .CK (clk), .D (n_25), .SE
       (n_101), .SI (rd_ptr[4]), .Q (rd_ptr[4]));
  SDFFRHQX1 \wr_ptr_reg[4] (.RN (n_179), .CK (clk), .D (n_24), .SE
       (n_33), .SI (wr_ptr[4]), .Q (wr_ptr[4]));
  OR3X1 g5687__8246(.A (n_32), .B (n_31), .C (n_101), .Y (n_43));
  NOR3X1 g5688__7098(.A (rd_ptr[3]), .B (rd_ptr[1]), .C (n_101), .Y
       (n_42));
  OR3X1 g5693__6131(.A (rd_ptr[1]), .B (n_32), .C (n_101), .Y (n_38));
  OR3X1 g5694__1881(.A (rd_ptr[3]), .B (n_31), .C (n_101), .Y (n_39));
  AND2X1 g5689__5115(.A (n_179), .B (n_30), .Y (n_45));
  INVX1 g5695(.A (n_101), .Y (n_29));
  INVX1 g5697(.A (n_33), .Y (n_30));
  OR2X2 g5696__7482(.A (n_0), .B (empty), .Y (n_101));
  NAND2BX1 g5698__4733(.AN (full), .B (wr_en), .Y (n_33));
  AND2X4 g5699__6161(.A (n_5), .B (n_26), .Y (empty));
  XOR2X1 g5692__9945(.A (rd_ptr[4]), .B (n_21), .Y (n_25));
  XOR2X1 g5651__2883(.A (wr_ptr[4]), .B (n_23), .Y (n_24));
  AOI21XL g5702__2346(.A0 (n_32), .A1 (n_19), .B0 (n_21), .Y (n_22));
  AND3XL g5703__1666(.A (n_11), .B (n_7), .C (n_18), .Y (n_26));
  ADDHXL g5686__7410(.A (wr_ptr[3]), .B (n_13), .CO (n_23), .S (n_20));
  NOR2XL g5705__6417(.A (n_32), .B (n_19), .Y (n_21));
  AOI221X1 g5706__5477(.A0 (rd_ptr[2]), .A1 (n_17), .B0 (wr_ptr[0]),
       .B1 (n_9), .C0 (n_10), .Y (n_18));
  OAI221X1 g5707__2398(.A0 (n_31), .A1 (n_37), .B0 (n_1), .B1
       (rd_ptr[1]), .C0 (n_40), .Y (n_16));
  NAND2X1 g5710__5107(.A (rd_ptr[1]), .B (n_15), .Y (n_19));
  AOI21XL g5704__6260(.A0 (n_17), .A1 (n_51), .B0 (n_13), .Y (n_14));
  INVX1 g5701(.A (n_13), .Y (n_12));
  MXI2XL g5714__4319(.A (rd_ptr[1]), .B (n_31), .S0 (wr_ptr[1]), .Y
       (n_11));
  OAI22XL g5709__8428(.A0 (wr_ptr[0]), .A1 (n_9), .B0 (rd_ptr[2]), .B1
       (n_17), .Y (n_10));
  NAND2X1 g5708__5526(.A (n_54), .B (n_75), .Y (n_8));
  MXI2XL g5715__6783(.A (rd_ptr[3]), .B (n_32), .S0 (wr_ptr[3]), .Y
       (n_7));
  INVX1 g5717(.A (n_44), .Y (n_15));
  MXI2XL g5713__3680(.A (n_31), .B (rd_ptr[1]), .S0 (rd_ptr[0]), .Y
       (n_2));
  NOR2XL g5711__1617(.A (n_17), .B (n_51), .Y (n_13));
  XNOR2X1 g5716__2802(.A (rd_ptr[4]), .B (wr_ptr[4]), .Y (n_5));
  INVX1 g5724(.A (n_54), .Y (n_48));
  OR2X1 g5721__1705(.A (n_9), .B (n_1), .Y (n_44));
  INVX1 g5722(.A (n_75), .Y (n_49));
  OR2X1 g5729__5122(.A (rd_ptr[2]), .B (n_9), .Y (n_37));
  OR2X1 g5727__8246(.A (rd_ptr[0]), .B (n_1), .Y (n_40));
  NOR2XL g5718__7098(.A (rd_ptr[0]), .B (rd_ptr[2]), .Y (n_47));
  NAND2BX1 g5726__6131(.AN (wr_ptr[1]), .B (wr_ptr[0]), .Y (n_75));
  NAND2BX1 g5728__1881(.AN (wr_ptr[0]), .B (wr_ptr[1]), .Y (n_54));
  NOR2X1 g5719__5115(.A (wr_ptr[1]), .B (wr_ptr[0]), .Y (n_53));
  NAND2X1 g5720__7482(.A (wr_ptr[1]), .B (wr_ptr[0]), .Y (n_51));
  INVX1 g5736(.A (rd_en), .Y (n_0));
  INVX1 g5735(.A (rst), .Y (n_179));
  SDFFRXL \rd_ptr_reg[0] (.RN (n_179), .CK (clk), .D (n_29), .SE
       (rd_ptr[0]), .SI (n_101), .Q (rd_ptr[0]), .QN (n_9));
  SDFFRXL \rd_ptr_reg[3] (.RN (n_179), .CK (clk), .D (n_22), .SE
       (n_101), .SI (rd_ptr[3]), .Q (rd_ptr[3]), .QN (n_32));
  SDFFRXL \rd_ptr_reg[1] (.RN (n_179), .CK (clk), .D (n_2), .SE
       (n_101), .SI (rd_ptr[1]), .Q (rd_ptr[1]), .QN (n_31));
  SDFFRXL \wr_ptr_reg[2] (.RN (n_179), .CK (clk), .D (n_14), .SE
       (n_33), .SI (wr_ptr[2]), .Q (wr_ptr[2]), .QN (n_17));
  SDFFRXL \wr_ptr_reg[3] (.RN (n_179), .CK (clk), .D (n_20), .SE
       (n_33), .SI (wr_ptr[3]), .Q (wr_ptr[3]), .QN (n_41));
  SDFFRXL \rd_ptr_reg[2] (.RN (n_179), .CK (clk), .D (n_16), .SE
       (n_101), .SI (rd_ptr[2]), .Q (rd_ptr[2]), .QN (n_1));
  NOR2BX1 g2(.AN (n_47), .B (n_38), .Y (n_184));
  NOR2BX1 g5896(.AN (n_47), .B (n_39), .Y (n_185));
  NOR2BX1 g5897(.AN (n_47), .B (n_43), .Y (n_186));
  NOR2BX4 g5898(.AN (n_26), .B (n_5), .Y (full));
  NOR2BX1 g5899(.AN (n_42), .B (n_37), .Y (n_188));
  NOR2BX1 g5900(.AN (n_42), .B (n_40), .Y (n_189));
endmodule

