
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Mar  5 2026 23:38:21 IST (Mar  5 2026 18:08:21 UTC)

// Verification Directory fv/sync_fifo 

module sync_fifo(clk, rst, wr_en, rd_en, wdata, rdata, full, empty);
  input clk, rst, wr_en, rd_en;
  input [7:0] wdata;
  output [7:0] rdata;
  output full, empty;
  wire clk, rst, wr_en, rd_en;
  wire [7:0] wdata;
  wire [7:0] rdata;
  wire full, empty;
  wire [7:0] \mem[15] ;
  wire [7:0] \mem[11] ;
  wire [7:0] \mem[10] ;
  wire [7:0] \mem[8] ;
  wire [7:0] \mem[9] ;
  wire [7:0] \mem[0] ;
  wire [7:0] \mem[1] ;
  wire [7:0] \mem[2] ;
  wire [7:0] \mem[5] ;
  wire [7:0] \mem[4] ;
  wire [7:0] \mem[12] ;
  wire [7:0] \mem[3] ;
  wire [7:0] \mem[6] ;
  wire [7:0] \mem[13] ;
  wire [7:0] \mem[14] ;
  wire [7:0] \mem[7] ;
  wire [4:0] wr_ptr;
  wire [4:0] rd_ptr;
  wire n_0, n_1, n_2, n_3, n_7, n_8, n_9, n_10;
  wire n_11, n_12, n_13, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_25, n_26, n_28;
  wire n_29, n_30, n_31, n_32, n_33, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_102, n_103, n_104;
  wire n_105, n_106, n_107, n_108, n_109, n_110, n_111, n_112;
  wire n_113, n_114, n_115, n_116, n_117, n_118, n_119, n_121;
  wire n_122, n_123, n_125, n_126, n_127, n_128, n_129, n_130;
  wire n_131, n_132, n_133, n_135, n_136, n_138, n_139, n_140;
  wire n_141, n_142, n_143, n_144, n_145, n_146, n_147, n_148;
  wire n_149, n_150, n_151, n_152, n_153, n_154, n_155, n_156;
  wire n_157, n_158, n_159, n_160, n_161, n_162, n_163, n_164;
  wire n_165, n_166, n_167, n_168, n_169, n_170, n_171, n_172;
  wire n_173, n_174, n_175, n_176, n_177, n_178, n_179, n_184;
  wire n_185, n_186, n_187, n_188;
  DFFRHQX4 \rdata_reg[0] (.RN (n_179), .CK (clk), .D (n_173), .Q
       (rdata[0]));
  DFFRHQX4 \rdata_reg[6] (.RN (n_179), .CK (clk), .D (n_178), .Q
       (rdata[6]));
  DFFRHQX4 \rdata_reg[7] (.RN (n_179), .CK (clk), .D (n_176), .Q
       (rdata[7]));
  DFFRHQX4 \rdata_reg[1] (.RN (n_179), .CK (clk), .D (n_175), .Q
       (rdata[1]));
  DFFRHQX4 \rdata_reg[2] (.RN (n_179), .CK (clk), .D (n_174), .Q
       (rdata[2]));
  DFFRHQX4 \rdata_reg[3] (.RN (n_179), .CK (clk), .D (n_177), .Q
       (rdata[3]));
  DFFRHQX4 \rdata_reg[4] (.RN (n_179), .CK (clk), .D (n_171), .Q
       (rdata[4]));
  DFFRHQX4 \rdata_reg[5] (.RN (n_179), .CK (clk), .D (n_172), .Q
       (rdata[5]));
  NAND4X1 g4709__2398(.A (n_86), .B (n_89), .C (n_135), .D (n_162), .Y
       (n_178));
  NAND4X1 g4708__5107(.A (n_59), .B (n_60), .C (n_138), .D (n_165), .Y
       (n_177));
  NAND4X1 g4704__6260(.A (n_84), .B (n_85), .C (n_131), .D (n_170), .Y
       (n_176));
  NAND4X1 g4705__4319(.A (n_126), .B (n_77), .C (n_136), .D (n_167), .Y
       (n_175));
  NAND4X1 g4702__8428(.A (n_106), .B (n_64), .C (n_130), .D (n_166), .Y
       (n_174));
  NAND4X1 g4703__5526(.A (n_102), .B (n_99), .C (n_149), .D (n_169), .Y
       (n_173));
  NAND4X1 g4706__6783(.A (n_53), .B (n_81), .C (n_133), .D (n_163), .Y
       (n_172));
  NAND4X1 g4707__3680(.A (n_55), .B (n_96), .C (n_132), .D (n_164), .Y
       (n_171));
  AOI21XL g4712__1617(.A0 (\mem[15] [7]), .A1 (n_168), .B0 (n_152), .Y
       (n_170));
  AOI21XL g4711__2802(.A0 (\mem[15] [0]), .A1 (n_168), .B0 (n_155), .Y
       (n_169));
  AOI21XL g4710__1705(.A0 (\mem[15] [1]), .A1 (n_168), .B0 (n_154), .Y
       (n_167));
  AOI21XL g4713__5122(.A0 (\mem[15] [2]), .A1 (n_168), .B0 (n_153), .Y
       (n_166));
  AOI21XL g4716__8246(.A0 (\mem[15] [3]), .A1 (n_168), .B0 (n_156), .Y
       (n_165));
  AOI21XL g4715__7098(.A0 (\mem[15] [4]), .A1 (n_168), .B0 (n_151), .Y
       (n_164));
  AOI21XL g4714__6131(.A0 (\mem[15] [5]), .A1 (n_168), .B0 (n_150), .Y
       (n_163));
  AOI21XL g4717__1881(.A0 (\mem[15] [6]), .A1 (n_168), .B0 (n_157), .Y
       (n_162));
  SDFFQX1 \mem_reg[11][3] (.CK (clk), .D (\mem[11] [3]), .SE (n_160),
       .SI (wdata[3]), .Q (\mem[11] [3]));
  SDFFQX1 \mem_reg[10][1] (.CK (clk), .D (\mem[10] [1]), .SE (n_159),
       .SI (wdata[1]), .Q (\mem[10] [1]));
  SDFFQX1 \mem_reg[8][1] (.CK (clk), .D (wdata[1]), .SE (n_161), .SI
       (\mem[8] [1]), .Q (\mem[8] [1]));
  SDFFQX1 \mem_reg[8][0] (.CK (clk), .D (wdata[0]), .SE (n_161), .SI
       (\mem[8] [0]), .Q (\mem[8] [0]));
  SDFFQX1 \mem_reg[8][2] (.CK (clk), .D (wdata[2]), .SE (n_161), .SI
       (\mem[8] [2]), .Q (\mem[8] [2]));
  SDFFQX1 \mem_reg[8][3] (.CK (clk), .D (wdata[3]), .SE (n_161), .SI
       (\mem[8] [3]), .Q (\mem[8] [3]));
  SDFFQX1 \mem_reg[8][5] (.CK (clk), .D (wdata[5]), .SE (n_161), .SI
       (\mem[8] [5]), .Q (\mem[8] [5]));
  SDFFQX1 \mem_reg[8][6] (.CK (clk), .D (wdata[6]), .SE (n_161), .SI
       (\mem[8] [6]), .Q (\mem[8] [6]));
  SDFFQX1 \mem_reg[8][4] (.CK (clk), .D (wdata[4]), .SE (n_161), .SI
       (\mem[8] [4]), .Q (\mem[8] [4]));
  SDFFQX1 \mem_reg[8][7] (.CK (clk), .D (wdata[7]), .SE (n_161), .SI
       (\mem[8] [7]), .Q (\mem[8] [7]));
  SDFFQX1 \mem_reg[11][7] (.CK (clk), .D (\mem[11] [7]), .SE (n_160),
       .SI (wdata[7]), .Q (\mem[11] [7]));
  SDFFQX1 \mem_reg[10][7] (.CK (clk), .D (\mem[10] [7]), .SE (n_159),
       .SI (wdata[7]), .Q (\mem[10] [7]));
  SDFFQX1 \mem_reg[11][0] (.CK (clk), .D (\mem[11] [0]), .SE (n_160),
       .SI (wdata[0]), .Q (\mem[11] [0]));
  SDFFQX1 \mem_reg[11][1] (.CK (clk), .D (\mem[11] [1]), .SE (n_160),
       .SI (wdata[1]), .Q (\mem[11] [1]));
  SDFFQX1 \mem_reg[11][2] (.CK (clk), .D (\mem[11] [2]), .SE (n_160),
       .SI (wdata[2]), .Q (\mem[11] [2]));
  SDFFQX1 \mem_reg[10][5] (.CK (clk), .D (\mem[10] [5]), .SE (n_159),
       .SI (wdata[5]), .Q (\mem[10] [5]));
  SDFFQX1 \mem_reg[10][6] (.CK (clk), .D (\mem[10] [6]), .SE (n_159),
       .SI (wdata[6]), .Q (\mem[10] [6]));
  SDFFQX1 \mem_reg[11][5] (.CK (clk), .D (\mem[11] [5]), .SE (n_160),
       .SI (wdata[5]), .Q (\mem[11] [5]));
  SDFFQX1 \mem_reg[11][6] (.CK (clk), .D (\mem[11] [6]), .SE (n_160),
       .SI (wdata[6]), .Q (\mem[11] [6]));
  SDFFQX1 \mem_reg[9][0] (.CK (clk), .D (\mem[9] [0]), .SE (n_158), .SI
       (wdata[0]), .Q (\mem[9] [0]));
  SDFFQX1 \mem_reg[9][1] (.CK (clk), .D (\mem[9] [1]), .SE (n_158), .SI
       (wdata[1]), .Q (\mem[9] [1]));
  SDFFQX1 \mem_reg[9][2] (.CK (clk), .D (\mem[9] [2]), .SE (n_158), .SI
       (wdata[2]), .Q (\mem[9] [2]));
  SDFFQX1 \mem_reg[9][3] (.CK (clk), .D (\mem[9] [3]), .SE (n_158), .SI
       (wdata[3]), .Q (\mem[9] [3]));
  SDFFQX1 \mem_reg[9][4] (.CK (clk), .D (\mem[9] [4]), .SE (n_158), .SI
       (wdata[4]), .Q (\mem[9] [4]));
  SDFFQX1 \mem_reg[9][5] (.CK (clk), .D (\mem[9] [5]), .SE (n_158), .SI
       (wdata[5]), .Q (\mem[9] [5]));
  SDFFQX1 \mem_reg[9][6] (.CK (clk), .D (\mem[9] [6]), .SE (n_158), .SI
       (wdata[6]), .Q (\mem[9] [6]));
  SDFFQX1 \mem_reg[9][7] (.CK (clk), .D (\mem[9] [7]), .SE (n_158), .SI
       (wdata[7]), .Q (\mem[9] [7]));
  SDFFQX1 \mem_reg[10][0] (.CK (clk), .D (\mem[10] [0]), .SE (n_159),
       .SI (wdata[0]), .Q (\mem[10] [0]));
  SDFFQX1 \mem_reg[10][2] (.CK (clk), .D (\mem[10] [2]), .SE (n_159),
       .SI (wdata[2]), .Q (\mem[10] [2]));
  SDFFQX1 \mem_reg[10][3] (.CK (clk), .D (\mem[10] [3]), .SE (n_159),
       .SI (wdata[3]), .Q (\mem[10] [3]));
  SDFFQX1 \mem_reg[10][4] (.CK (clk), .D (\mem[10] [4]), .SE (n_159),
       .SI (wdata[4]), .Q (\mem[10] [4]));
  SDFFQX1 \mem_reg[11][4] (.CK (clk), .D (\mem[11] [4]), .SE (n_160),
       .SI (wdata[4]), .Q (\mem[11] [4]));
  NAND4X1 g4785__5115(.A (n_118), .B (n_80), .C (n_122), .D (n_95), .Y
       (n_157));
  NAND4X1 g4778__7482(.A (n_57), .B (n_67), .C (n_108), .D (n_116), .Y
       (n_156));
  NAND4X1 g4779__4733(.A (n_114), .B (n_70), .C (n_113), .D (n_69), .Y
       (n_155));
  NAND4X1 g4780__6161(.A (n_117), .B (n_58), .C (n_125), .D (n_66), .Y
       (n_154));
  NAND4X1 g4781__9315(.A (n_111), .B (n_63), .C (n_110), .D (n_62), .Y
       (n_153));
  NAND4X1 g4782__9945(.A (n_128), .B (n_82), .C (n_119), .D (n_92), .Y
       (n_152));
  NAND4X1 g4783__2883(.A (n_109), .B (n_54), .C (n_107), .D (n_83), .Y
       (n_151));
  NAND4X1 g4784__2346(.A (n_127), .B (n_52), .C (n_104), .D (n_51), .Y
       (n_150));
  AOI221X1 g4856__1666(.A0 (\mem[0] [0]), .A1 (n_105), .B0 (\mem[1]
       [0]), .B1 (n_188), .C0 (n_115), .Y (n_149));
  SDFFQX1 \mem_reg[2][6] (.CK (clk), .D (wdata[6]), .SE (n_143), .SI
       (\mem[2] [6]), .Q (\mem[2] [6]));
  SDFFQX1 \mem_reg[1][3] (.CK (clk), .D (wdata[3]), .SE (n_148), .SI
       (\mem[1] [3]), .Q (\mem[1] [3]));
  SDFFQX1 \mem_reg[5][7] (.CK (clk), .D (\mem[5] [7]), .SE (n_141), .SI
       (wdata[7]), .Q (\mem[5] [7]));
  SDFFQX1 \mem_reg[1][7] (.CK (clk), .D (wdata[7]), .SE (n_148), .SI
       (\mem[1] [7]), .Q (\mem[1] [7]));
  SDFFQX1 \mem_reg[1][2] (.CK (clk), .D (wdata[2]), .SE (n_148), .SI
       (\mem[1] [2]), .Q (\mem[1] [2]));
  SDFFQX1 \mem_reg[4][3] (.CK (clk), .D (wdata[3]), .SE (n_145), .SI
       (\mem[4] [3]), .Q (\mem[4] [3]));
  SDFFQX1 \mem_reg[0][2] (.CK (clk), .D (wdata[2]), .SE (n_147), .SI
       (\mem[0] [2]), .Q (\mem[0] [2]));
  SDFFQX1 \mem_reg[0][0] (.CK (clk), .D (wdata[0]), .SE (n_147), .SI
       (\mem[0] [0]), .Q (\mem[0] [0]));
  SDFFQX1 \mem_reg[0][3] (.CK (clk), .D (wdata[3]), .SE (n_147), .SI
       (\mem[0] [3]), .Q (\mem[0] [3]));
  SDFFQX1 \mem_reg[0][1] (.CK (clk), .D (wdata[1]), .SE (n_147), .SI
       (\mem[0] [1]), .Q (\mem[0] [1]));
  SDFFQX1 \mem_reg[0][5] (.CK (clk), .D (wdata[5]), .SE (n_147), .SI
       (\mem[0] [5]), .Q (\mem[0] [5]));
  SDFFQX1 \mem_reg[0][4] (.CK (clk), .D (wdata[4]), .SE (n_147), .SI
       (\mem[0] [4]), .Q (\mem[0] [4]));
  SDFFQX1 \mem_reg[0][6] (.CK (clk), .D (wdata[6]), .SE (n_147), .SI
       (\mem[0] [6]), .Q (\mem[0] [6]));
  SDFFQX1 \mem_reg[12][0] (.CK (clk), .D (wdata[0]), .SE (n_146), .SI
       (\mem[12] [0]), .Q (\mem[12] [0]));
  SDFFQX1 \mem_reg[12][1] (.CK (clk), .D (wdata[1]), .SE (n_146), .SI
       (\mem[12] [1]), .Q (\mem[12] [1]));
  SDFFQX1 \mem_reg[12][2] (.CK (clk), .D (wdata[2]), .SE (n_146), .SI
       (\mem[12] [2]), .Q (\mem[12] [2]));
  SDFFQX1 \mem_reg[12][3] (.CK (clk), .D (wdata[3]), .SE (n_146), .SI
       (\mem[12] [3]), .Q (\mem[12] [3]));
  SDFFQX1 \mem_reg[12][4] (.CK (clk), .D (wdata[4]), .SE (n_146), .SI
       (\mem[12] [4]), .Q (\mem[12] [4]));
  SDFFQX1 \mem_reg[12][5] (.CK (clk), .D (wdata[5]), .SE (n_146), .SI
       (\mem[12] [5]), .Q (\mem[12] [5]));
  SDFFQX1 \mem_reg[12][6] (.CK (clk), .D (wdata[6]), .SE (n_146), .SI
       (\mem[12] [6]), .Q (\mem[12] [6]));
  SDFFQX1 \mem_reg[4][6] (.CK (clk), .D (wdata[6]), .SE (n_145), .SI
       (\mem[4] [6]), .Q (\mem[4] [6]));
  SDFFQX1 \mem_reg[4][7] (.CK (clk), .D (wdata[7]), .SE (n_145), .SI
       (\mem[4] [7]), .Q (\mem[4] [7]));
  SDFFQX1 \mem_reg[4][5] (.CK (clk), .D (wdata[5]), .SE (n_145), .SI
       (\mem[4] [5]), .Q (\mem[4] [5]));
  SDFFQX1 \mem_reg[12][7] (.CK (clk), .D (wdata[7]), .SE (n_146), .SI
       (\mem[12] [7]), .Q (\mem[12] [7]));
  SDFFQX1 \mem_reg[0][7] (.CK (clk), .D (wdata[7]), .SE (n_147), .SI
       (\mem[0] [7]), .Q (\mem[0] [7]));
  SDFFQX1 \mem_reg[3][1] (.CK (clk), .D (\mem[3] [1]), .SE (n_144), .SI
       (wdata[1]), .Q (\mem[3] [1]));
  SDFFQX1 \mem_reg[4][1] (.CK (clk), .D (wdata[1]), .SE (n_145), .SI
       (\mem[4] [1]), .Q (\mem[4] [1]));
  SDFFQX1 \mem_reg[4][0] (.CK (clk), .D (wdata[0]), .SE (n_145), .SI
       (\mem[4] [0]), .Q (\mem[4] [0]));
  SDFFQX1 \mem_reg[4][2] (.CK (clk), .D (wdata[2]), .SE (n_145), .SI
       (\mem[4] [2]), .Q (\mem[4] [2]));
  SDFFQX1 \mem_reg[4][4] (.CK (clk), .D (wdata[4]), .SE (n_145), .SI
       (\mem[4] [4]), .Q (\mem[4] [4]));
  SDFFQX1 \mem_reg[1][5] (.CK (clk), .D (wdata[5]), .SE (n_148), .SI
       (\mem[1] [5]), .Q (\mem[1] [5]));
  SDFFQX1 \mem_reg[1][6] (.CK (clk), .D (wdata[6]), .SE (n_148), .SI
       (\mem[1] [6]), .Q (\mem[1] [6]));
  SDFFQX1 \mem_reg[1][0] (.CK (clk), .D (wdata[0]), .SE (n_148), .SI
       (\mem[1] [0]), .Q (\mem[1] [0]));
  SDFFQX1 \mem_reg[1][1] (.CK (clk), .D (wdata[1]), .SE (n_148), .SI
       (\mem[1] [1]), .Q (\mem[1] [1]));
  SDFFQX1 \mem_reg[3][5] (.CK (clk), .D (\mem[3] [5]), .SE (n_144), .SI
       (wdata[5]), .Q (\mem[3] [5]));
  SDFFQX1 \mem_reg[6][3] (.CK (clk), .D (\mem[6] [3]), .SE (n_142), .SI
       (wdata[3]), .Q (\mem[6] [3]));
  SDFFQX1 \mem_reg[2][0] (.CK (clk), .D (wdata[0]), .SE (n_143), .SI
       (\mem[2] [0]), .Q (\mem[2] [0]));
  SDFFQX1 \mem_reg[2][1] (.CK (clk), .D (wdata[1]), .SE (n_143), .SI
       (\mem[2] [1]), .Q (\mem[2] [1]));
  SDFFQX1 \mem_reg[2][2] (.CK (clk), .D (wdata[2]), .SE (n_143), .SI
       (\mem[2] [2]), .Q (\mem[2] [2]));
  SDFFQX1 \mem_reg[2][3] (.CK (clk), .D (wdata[3]), .SE (n_143), .SI
       (\mem[2] [3]), .Q (\mem[2] [3]));
  SDFFQX1 \mem_reg[2][4] (.CK (clk), .D (wdata[4]), .SE (n_143), .SI
       (\mem[2] [4]), .Q (\mem[2] [4]));
  SDFFQX1 \mem_reg[2][5] (.CK (clk), .D (wdata[5]), .SE (n_143), .SI
       (\mem[2] [5]), .Q (\mem[2] [5]));
  SDFFQX1 \mem_reg[6][6] (.CK (clk), .D (\mem[6] [6]), .SE (n_142), .SI
       (wdata[6]), .Q (\mem[6] [6]));
  SDFFQX1 \mem_reg[1][4] (.CK (clk), .D (wdata[4]), .SE (n_148), .SI
       (\mem[1] [4]), .Q (\mem[1] [4]));
  SDFFQX1 \mem_reg[2][7] (.CK (clk), .D (wdata[7]), .SE (n_143), .SI
       (\mem[2] [7]), .Q (\mem[2] [7]));
  SDFFQX1 \mem_reg[5][0] (.CK (clk), .D (\mem[5] [0]), .SE (n_141), .SI
       (wdata[0]), .Q (\mem[5] [0]));
  SDFFQX1 \mem_reg[5][1] (.CK (clk), .D (\mem[5] [1]), .SE (n_141), .SI
       (wdata[1]), .Q (\mem[5] [1]));
  SDFFQX1 \mem_reg[13][2] (.CK (clk), .D (\mem[13] [2]), .SE (n_140),
       .SI (wdata[2]), .Q (\mem[13] [2]));
  SDFFQX1 \mem_reg[13][3] (.CK (clk), .D (\mem[13] [3]), .SE (n_140),
       .SI (wdata[3]), .Q (\mem[13] [3]));
  SDFFQX1 \mem_reg[6][0] (.CK (clk), .D (\mem[6] [0]), .SE (n_142), .SI
       (wdata[0]), .Q (\mem[6] [0]));
  SDFFQX1 \mem_reg[13][5] (.CK (clk), .D (\mem[13] [5]), .SE (n_140),
       .SI (wdata[5]), .Q (\mem[13] [5]));
  SDFFQX1 \mem_reg[6][1] (.CK (clk), .D (\mem[6] [1]), .SE (n_142), .SI
       (wdata[1]), .Q (\mem[6] [1]));
  SDFFQX1 \mem_reg[13][6] (.CK (clk), .D (\mem[13] [6]), .SE (n_140),
       .SI (wdata[6]), .Q (\mem[13] [6]));
  SDFFQX1 \mem_reg[13][7] (.CK (clk), .D (\mem[13] [7]), .SE (n_140),
       .SI (wdata[7]), .Q (\mem[13] [7]));
  SDFFQX1 \mem_reg[14][0] (.CK (clk), .D (\mem[14] [0]), .SE (n_139),
       .SI (wdata[0]), .Q (\mem[14] [0]));
  SDFFQX1 \mem_reg[14][1] (.CK (clk), .D (\mem[14] [1]), .SE (n_139),
       .SI (wdata[1]), .Q (\mem[14] [1]));
  SDFFQX1 \mem_reg[14][3] (.CK (clk), .D (\mem[14] [3]), .SE (n_139),
       .SI (wdata[3]), .Q (\mem[14] [3]));
  SDFFQX1 \mem_reg[6][4] (.CK (clk), .D (\mem[6] [4]), .SE (n_142), .SI
       (wdata[4]), .Q (\mem[6] [4]));
  SDFFQX1 \mem_reg[14][4] (.CK (clk), .D (\mem[14] [4]), .SE (n_139),
       .SI (wdata[4]), .Q (\mem[14] [4]));
  SDFFQX1 \mem_reg[6][5] (.CK (clk), .D (\mem[6] [5]), .SE (n_142), .SI
       (wdata[5]), .Q (\mem[6] [5]));
  SDFFQX1 \mem_reg[14][5] (.CK (clk), .D (\mem[14] [5]), .SE (n_139),
       .SI (wdata[5]), .Q (\mem[14] [5]));
  SDFFQX1 \mem_reg[14][6] (.CK (clk), .D (\mem[14] [6]), .SE (n_139),
       .SI (wdata[6]), .Q (\mem[14] [6]));
  SDFFQX1 \mem_reg[14][7] (.CK (clk), .D (\mem[14] [7]), .SE (n_139),
       .SI (wdata[7]), .Q (\mem[14] [7]));
  SDFFQX1 \mem_reg[6][7] (.CK (clk), .D (\mem[6] [7]), .SE (n_142), .SI
       (wdata[7]), .Q (\mem[6] [7]));
  SDFFQX1 \mem_reg[5][2] (.CK (clk), .D (\mem[5] [2]), .SE (n_141), .SI
       (wdata[2]), .Q (\mem[5] [2]));
  SDFFQX1 \mem_reg[3][2] (.CK (clk), .D (\mem[3] [2]), .SE (n_144), .SI
       (wdata[2]), .Q (\mem[3] [2]));
  SDFFQX1 \mem_reg[3][3] (.CK (clk), .D (\mem[3] [3]), .SE (n_144), .SI
       (wdata[3]), .Q (\mem[3] [3]));
  SDFFQX1 \mem_reg[3][4] (.CK (clk), .D (\mem[3] [4]), .SE (n_144), .SI
       (wdata[4]), .Q (\mem[3] [4]));
  SDFFQX1 \mem_reg[6][2] (.CK (clk), .D (\mem[6] [2]), .SE (n_142), .SI
       (wdata[2]), .Q (\mem[6] [2]));
  SDFFQX1 \mem_reg[3][6] (.CK (clk), .D (\mem[3] [6]), .SE (n_144), .SI
       (wdata[6]), .Q (\mem[3] [6]));
  SDFFQX1 \mem_reg[3][7] (.CK (clk), .D (\mem[3] [7]), .SE (n_144), .SI
       (wdata[7]), .Q (\mem[3] [7]));
  SDFFQX1 \mem_reg[14][2] (.CK (clk), .D (\mem[14] [2]), .SE (n_139),
       .SI (wdata[2]), .Q (\mem[14] [2]));
  SDFFQX1 \mem_reg[13][4] (.CK (clk), .D (\mem[13] [4]), .SE (n_140),
       .SI (wdata[4]), .Q (\mem[13] [4]));
  SDFFQX1 \mem_reg[3][0] (.CK (clk), .D (\mem[3] [0]), .SE (n_144), .SI
       (wdata[0]), .Q (\mem[3] [0]));
  SDFFQX1 \mem_reg[5][3] (.CK (clk), .D (\mem[5] [3]), .SE (n_141), .SI
       (wdata[3]), .Q (\mem[5] [3]));
  SDFFQX1 \mem_reg[5][4] (.CK (clk), .D (\mem[5] [4]), .SE (n_141), .SI
       (wdata[4]), .Q (\mem[5] [4]));
  SDFFQX1 \mem_reg[5][5] (.CK (clk), .D (\mem[5] [5]), .SE (n_141), .SI
       (wdata[5]), .Q (\mem[5] [5]));
  SDFFQX1 \mem_reg[5][6] (.CK (clk), .D (\mem[5] [6]), .SE (n_141), .SI
       (wdata[6]), .Q (\mem[5] [6]));
  SDFFQX1 \mem_reg[13][0] (.CK (clk), .D (\mem[13] [0]), .SE (n_140),
       .SI (wdata[0]), .Q (\mem[13] [0]));
  SDFFQX1 \mem_reg[13][1] (.CK (clk), .D (\mem[13] [1]), .SE (n_140),
       .SI (wdata[1]), .Q (\mem[13] [1]));
  AOI221X1 g4857__7410(.A0 (\mem[1] [3]), .A1 (n_188), .B0 (\mem[2]
       [3]), .B1 (n_186), .C0 (n_61), .Y (n_138));
  AOI221X1 g4851__6417(.A0 (\mem[5] [1]), .A1 (n_98), .B0 (\mem[6]
       [1]), .B1 (n_97), .C0 (n_68), .Y (n_136));
  AOI221X1 g4852__5477(.A0 (\mem[1] [6]), .A1 (n_188), .B0 (\mem[2]
       [6]), .B1 (n_186), .C0 (n_94), .Y (n_135));
  AOI221X1 g4853__2398(.A0 (\mem[1] [5]), .A1 (n_188), .B0 (\mem[2]
       [5]), .B1 (n_186), .C0 (n_56), .Y (n_133));
  AOI221X1 g4854__5107(.A0 (\mem[1] [4]), .A1 (n_188), .B0 (\mem[2]
       [4]), .B1 (n_186), .C0 (n_87), .Y (n_132));
  AOI221X1 g4855__6260(.A0 (\mem[1] [7]), .A1 (n_188), .B0 (\mem[2]
       [7]), .B1 (n_186), .C0 (n_88), .Y (n_131));
  SDFFQX1 \mem_reg[7][5] (.CK (clk), .D (wdata[5]), .SE (n_129), .SI
       (\mem[7] [5]), .Q (\mem[7] [5]));
  AOI221X1 g4858__4319(.A0 (\mem[4] [2]), .A1 (n_187), .B0 (\mem[3]
       [2]), .B1 (n_100), .C0 (n_65), .Y (n_130));
  SDFFQX1 \mem_reg[7][0] (.CK (clk), .D (wdata[0]), .SE (n_129), .SI
       (\mem[7] [0]), .Q (\mem[7] [0]));
  SDFFQX1 \mem_reg[7][1] (.CK (clk), .D (wdata[1]), .SE (n_129), .SI
       (\mem[7] [1]), .Q (\mem[7] [1]));
  SDFFQX1 \mem_reg[7][2] (.CK (clk), .D (wdata[2]), .SE (n_129), .SI
       (\mem[7] [2]), .Q (\mem[7] [2]));
  SDFFQX1 \mem_reg[7][3] (.CK (clk), .D (wdata[3]), .SE (n_129), .SI
       (\mem[7] [3]), .Q (\mem[7] [3]));
  SDFFQX1 \mem_reg[7][6] (.CK (clk), .D (wdata[6]), .SE (n_129), .SI
       (\mem[7] [6]), .Q (\mem[7] [6]));
  SDFFQX1 \mem_reg[7][7] (.CK (clk), .D (wdata[7]), .SE (n_129), .SI
       (\mem[7] [7]), .Q (\mem[7] [7]));
  SDFFQX1 \mem_reg[7][4] (.CK (clk), .D (wdata[4]), .SE (n_129), .SI
       (\mem[7] [4]), .Q (\mem[7] [4]));
  AOI22X1 g4874__8428(.A0 (\mem[9] [7]), .A1 (n_121), .B0 (\mem[10]
       [7]), .B1 (n_184), .Y (n_128));
  AOI22X1 g4918__5526(.A0 (\mem[8] [5]), .A1 (n_185), .B0 (\mem[7]
       [5]), .B1 (n_123), .Y (n_127));
  AOI22X1 g4864__6783(.A0 (\mem[1] [1]), .A1 (n_188), .B0 (\mem[2]
       [1]), .B1 (n_186), .Y (n_126));
  AOI22X1 g4895__3680(.A0 (\mem[8] [1]), .A1 (n_185), .B0 (\mem[7]
       [1]), .B1 (n_123), .Y (n_125));
  AOI22X1 g4865__1617(.A0 (\mem[9] [6]), .A1 (n_121), .B0 (\mem[10]
       [6]), .B1 (n_184), .Y (n_122));
  AOI22X1 g4872__2802(.A0 (\mem[8] [7]), .A1 (n_185), .B0 (\mem[7]
       [7]), .B1 (n_123), .Y (n_119));
  AOI22X1 g4873__1705(.A0 (\mem[8] [6]), .A1 (n_185), .B0 (\mem[7]
       [6]), .B1 (n_123), .Y (n_118));
  AOI22X1 g4893__5122(.A0 (\mem[9] [1]), .A1 (n_121), .B0 (\mem[10]
       [1]), .B1 (n_184), .Y (n_117));
  AOI22X1 g4875__8246(.A0 (\mem[9] [3]), .A1 (n_121), .B0 (\mem[10]
       [3]), .B1 (n_184), .Y (n_116));
  AO22XL g4882__7098(.A0 (\mem[2] [0]), .A1 (n_186), .B0 (rdata[0]),
       .B1 (n_93), .Y (n_115));
  AOI22X1 g4886__6131(.A0 (\mem[8] [0]), .A1 (n_185), .B0 (\mem[7]
       [0]), .B1 (n_123), .Y (n_114));
  AOI22X1 g4888__1881(.A0 (\mem[9] [0]), .A1 (n_121), .B0 (\mem[10]
       [0]), .B1 (n_184), .Y (n_113));
  SDFFQX1 \mem_reg[15][0] (.CK (clk), .D (wdata[0]), .SE (n_112), .SI
       (\mem[15] [0]), .Q (\mem[15] [0]));
  SDFFQX1 \mem_reg[15][2] (.CK (clk), .D (wdata[2]), .SE (n_112), .SI
       (\mem[15] [2]), .Q (\mem[15] [2]));
  NOR2X2 g4942__5115(.A (n_73), .B (n_103), .Y (n_158));
  AOI22X1 g4900__7482(.A0 (\mem[8] [2]), .A1 (n_185), .B0 (\mem[7]
       [2]), .B1 (n_123), .Y (n_111));
  AOI22X1 g4902__4733(.A0 (\mem[9] [2]), .A1 (n_121), .B0 (\mem[10]
       [2]), .B1 (n_184), .Y (n_110));
  AOI22X1 g4913__6161(.A0 (\mem[8] [4]), .A1 (n_185), .B0 (\mem[7]
       [4]), .B1 (n_123), .Y (n_109));
  AOI22X1 g4909__9315(.A0 (\mem[8] [3]), .A1 (n_185), .B0 (\mem[7]
       [3]), .B1 (n_123), .Y (n_108));
  AOI22X1 g4914__9945(.A0 (\mem[9] [4]), .A1 (n_121), .B0 (\mem[10]
       [4]), .B1 (n_184), .Y (n_107));
  AOI22X1 g4898__2883(.A0 (\mem[0] [2]), .A1 (n_105), .B0 (\mem[2]
       [2]), .B1 (n_186), .Y (n_106));
  AOI22X1 g4919__2346(.A0 (\mem[9] [5]), .A1 (n_121), .B0 (\mem[10]
       [5]), .B1 (n_184), .Y (n_104));
  SDFFQX1 \mem_reg[15][4] (.CK (clk), .D (wdata[4]), .SE (n_112), .SI
       (\mem[15] [4]), .Q (\mem[15] [4]));
  SDFFQX1 \mem_reg[15][5] (.CK (clk), .D (wdata[5]), .SE (n_112), .SI
       (\mem[15] [5]), .Q (\mem[15] [5]));
  SDFFQX1 \mem_reg[15][7] (.CK (clk), .D (wdata[7]), .SE (n_112), .SI
       (\mem[15] [7]), .Q (\mem[15] [7]));
  SDFFQX1 \mem_reg[15][3] (.CK (clk), .D (wdata[3]), .SE (n_112), .SI
       (\mem[15] [3]), .Q (\mem[15] [3]));
  SDFFQX1 \mem_reg[15][1] (.CK (clk), .D (wdata[1]), .SE (n_112), .SI
       (\mem[15] [1]), .Q (\mem[15] [1]));
  SDFFQX1 \mem_reg[15][6] (.CK (clk), .D (wdata[6]), .SE (n_112), .SI
       (\mem[15] [6]), .Q (\mem[15] [6]));
  NAND2BX2 g4929__1666(.AN (n_103), .B (n_71), .Y (n_161));
  NOR2X2 g4931__7410(.A (n_75), .B (n_103), .Y (n_160));
  NOR2X2 g4934__6417(.A (n_48), .B (n_103), .Y (n_159));
  AOI22X1 g4884__5477(.A0 (\mem[4] [0]), .A1 (n_187), .B0 (\mem[3]
       [0]), .B1 (n_100), .Y (n_102));
  AOI22X1 g4883__2398(.A0 (\mem[5] [0]), .A1 (n_98), .B0 (\mem[6] [0]),
       .B1 (n_97), .Y (n_99));
  AOI22X1 g4881__5107(.A0 (\mem[5] [4]), .A1 (n_98), .B0 (\mem[6] [4]),
       .B1 (n_97), .Y (n_96));
  AOI22X1 g4880__6260(.A0 (\mem[12] [6]), .A1 (n_91), .B0 (\mem[11]
       [6]), .B1 (n_90), .Y (n_95));
  AO22XL g4879__4319(.A0 (\mem[0] [6]), .A1 (n_105), .B0 (rdata[6]),
       .B1 (n_93), .Y (n_94));
  AOI22X1 g4878__8428(.A0 (\mem[12] [7]), .A1 (n_91), .B0 (\mem[11]
       [7]), .B1 (n_90), .Y (n_92));
  AOI22X1 g4863__5526(.A0 (\mem[5] [6]), .A1 (n_98), .B0 (\mem[6] [6]),
       .B1 (n_97), .Y (n_89));
  AO22XL g4866__6783(.A0 (\mem[6] [7]), .A1 (n_97), .B0 (rdata[7]), .B1
       (n_93), .Y (n_88));
  AO22XL g4910__3680(.A0 (\mem[0] [4]), .A1 (n_105), .B0 (rdata[4]),
       .B1 (n_93), .Y (n_87));
  AOI22X1 g4867__1617(.A0 (\mem[4] [6]), .A1 (n_187), .B0 (\mem[3]
       [6]), .B1 (n_100), .Y (n_86));
  AOI22X1 g4868__2802(.A0 (\mem[4] [7]), .A1 (n_187), .B0 (\mem[3]
       [7]), .B1 (n_100), .Y (n_85));
  AOI22X1 g4869__1705(.A0 (\mem[0] [7]), .A1 (n_105), .B0 (\mem[5]
       [7]), .B1 (n_98), .Y (n_84));
  AOI22X1 g4870__5122(.A0 (\mem[12] [4]), .A1 (n_91), .B0 (\mem[11]
       [4]), .B1 (n_90), .Y (n_83));
  AOI22X1 g4871__8246(.A0 (\mem[13] [7]), .A1 (n_79), .B0 (\mem[14]
       [7]), .B1 (n_78), .Y (n_82));
  AOI22X1 g4915__7098(.A0 (\mem[5] [5]), .A1 (n_98), .B0 (\mem[6] [5]),
       .B1 (n_97), .Y (n_81));
  AOI22X1 g4876__6131(.A0 (\mem[13] [6]), .A1 (n_79), .B0 (\mem[14]
       [6]), .B1 (n_78), .Y (n_80));
  AOI22X1 g4877__1881(.A0 (\mem[4] [1]), .A1 (n_187), .B0 (\mem[3]
       [1]), .B1 (n_100), .Y (n_77));
  NAND2X2 g4941__5115(.A (n_74), .B (n_76), .Y (n_148));
  NAND2X2 g4940__7482(.A (n_50), .B (n_76), .Y (n_143));
  NOR2BX2 g4939__4733(.AN (n_76), .B (n_75), .Y (n_144));
  AND2X1 g4938__6161(.A (n_74), .B (n_49), .Y (n_140));
  NOR2X2 g4936__9315(.A (n_73), .B (n_72), .Y (n_141));
  NAND2BX2 g4937__9945(.AN (n_72), .B (n_71), .Y (n_145));
  AOI22X1 g4885__2883(.A0 (\mem[13] [0]), .A1 (n_79), .B0 (\mem[14]
       [0]), .B1 (n_78), .Y (n_70));
  AOI22X1 g4887__2346(.A0 (\mem[12] [0]), .A1 (n_91), .B0 (\mem[11]
       [0]), .B1 (n_90), .Y (n_69));
  AO22XL g4889__1666(.A0 (\mem[0] [1]), .A1 (n_105), .B0 (rdata[1]),
       .B1 (n_93), .Y (n_68));
  AOI22X1 g4892__7410(.A0 (\mem[13] [3]), .A1 (n_79), .B0 (\mem[14]
       [3]), .B1 (n_78), .Y (n_67));
  AOI22X1 g4894__6417(.A0 (\mem[12] [1]), .A1 (n_91), .B0 (\mem[11]
       [1]), .B1 (n_90), .Y (n_66));
  AO22XL g4896__5477(.A0 (\mem[1] [2]), .A1 (n_188), .B0 (rdata[2]),
       .B1 (n_93), .Y (n_65));
  AOI22X1 g4897__2398(.A0 (\mem[5] [2]), .A1 (n_98), .B0 (\mem[6] [2]),
       .B1 (n_97), .Y (n_64));
  AOI22X1 g4899__5107(.A0 (\mem[13] [2]), .A1 (n_79), .B0 (\mem[14]
       [2]), .B1 (n_78), .Y (n_63));
  AOI22X1 g4901__6260(.A0 (\mem[12] [2]), .A1 (n_91), .B0 (\mem[11]
       [2]), .B1 (n_90), .Y (n_62));
  AO22XL g4903__4319(.A0 (\mem[0] [3]), .A1 (n_105), .B0 (rdata[3]),
       .B1 (n_93), .Y (n_61));
  AOI22X1 g4904__8428(.A0 (\mem[5] [3]), .A1 (n_98), .B0 (\mem[6] [3]),
       .B1 (n_97), .Y (n_60));
  AOI22X1 g4905__5526(.A0 (\mem[4] [3]), .A1 (n_187), .B0 (\mem[3]
       [3]), .B1 (n_100), .Y (n_59));
  AOI22X1 g4906__6783(.A0 (\mem[13] [1]), .A1 (n_79), .B0 (\mem[14]
       [1]), .B1 (n_78), .Y (n_58));
  AOI22X1 g4907__3680(.A0 (\mem[12] [3]), .A1 (n_91), .B0 (\mem[11]
       [3]), .B1 (n_90), .Y (n_57));
  AO22XL g4908__1617(.A0 (\mem[0] [5]), .A1 (n_105), .B0 (rdata[5]),
       .B1 (n_93), .Y (n_56));
  AOI22X1 g4911__2802(.A0 (\mem[4] [4]), .A1 (n_187), .B0 (\mem[3]
       [4]), .B1 (n_100), .Y (n_55));
  AOI22X1 g4912__1705(.A0 (\mem[13] [4]), .A1 (n_79), .B0 (\mem[14]
       [4]), .B1 (n_78), .Y (n_54));
  AOI22X1 g4916__5122(.A0 (\mem[4] [5]), .A1 (n_187), .B0 (\mem[3]
       [5]), .B1 (n_100), .Y (n_53));
  AOI22X1 g4917__8246(.A0 (\mem[13] [5]), .A1 (n_79), .B0 (\mem[14]
       [5]), .B1 (n_78), .Y (n_52));
  AOI22X1 g4920__7098(.A0 (\mem[12] [5]), .A1 (n_91), .B0 (\mem[11]
       [5]), .B1 (n_90), .Y (n_51));
  AND2X1 g4935__6131(.A (n_50), .B (n_49), .Y (n_139));
  NOR2X2 g4933__1881(.A (n_48), .B (n_72), .Y (n_142));
  NAND2X2 g4930__5115(.A (n_71), .B (n_76), .Y (n_147));
  NAND2X2 g4928__7482(.A (n_71), .B (n_49), .Y (n_146));
  OR3X1 g4957__4733(.A (wr_ptr[2]), .B (n_44), .C (n_47), .Y (n_103));
  OR3X1 g4964__6161(.A (wr_ptr[3]), .B (n_47), .C (n_12), .Y (n_129));
  NAND3BX1 g4955__2346(.AN (wr_ptr[3]), .B (wr_ptr[2]), .C (n_45), .Y
       (n_72));
  AND3XL g4954__1666(.A (wr_ptr[3]), .B (wr_ptr[2]), .C (n_45), .Y
       (n_49));
  AND3XL g4956__7410(.A (n_44), .B (n_16), .C (n_45), .Y (n_76));
  NOR2X1 g4950__6417(.A (n_42), .B (n_39), .Y (n_79));
  AND2X1 g4944__5477(.A (n_46), .B (n_43), .Y (n_105));
  AND2X1 g4945__2398(.A (n_13), .B (n_43), .Y (n_98));
  NOR2X1 g4949__5107(.A (n_42), .B (n_38), .Y (n_123));
  NOR2X1 g4943__6260(.A (n_42), .B (n_41), .Y (n_168));
  NOR2X1 g4951__4319(.A (n_37), .B (n_41), .Y (n_78));
  NOR2X1 g4952__8428(.A (n_40), .B (n_41), .Y (n_90));
  NAND2X2 g4953__5526(.A (n_45), .B (n_25), .Y (n_112));
  NOR2X1 g4960__6783(.A (n_40), .B (n_39), .Y (n_121));
  NOR2X1 g4958__1617(.A (n_40), .B (n_38), .Y (n_100));
  NOR2X1 g4963__2802(.A (n_37), .B (n_39), .Y (n_91));
  NOR2X1 g4962__1705(.A (n_37), .B (n_38), .Y (n_97));
  INVX1 g4966(.A (n_45), .Y (n_47));
  SDFFRHQX1 \rd_ptr_reg[4] (.RN (n_179), .CK (clk), .D (n_28), .SE
       (n_93), .SI (rd_ptr[4]), .Q (rd_ptr[4]));
  SDFFRHQX1 \wr_ptr_reg[4] (.RN (n_179), .CK (clk), .D (n_26), .SE
       (n_33), .SI (wr_ptr[4]), .Q (wr_ptr[4]));
  SDFFRHQX1 \wr_ptr_reg[1] (.RN (n_179), .CK (clk), .D (n_14), .SE
       (n_33), .SI (wr_ptr[1]), .Q (wr_ptr[1]));
  OR3X1 g4968__8246(.A (n_32), .B (n_31), .C (n_93), .Y (n_41));
  NOR3X1 g4969__7098(.A (rd_ptr[3]), .B (rd_ptr[1]), .C (n_93), .Y
       (n_43));
  OR3X1 g4974__6131(.A (rd_ptr[1]), .B (n_32), .C (n_93), .Y (n_39));
  OR3X1 g4975__1881(.A (rd_ptr[3]), .B (n_31), .C (n_93), .Y (n_38));
  AND2X1 g4970__5115(.A (n_179), .B (n_30), .Y (n_45));
  INVX1 g4976(.A (n_93), .Y (n_29));
  INVX1 g4978(.A (n_33), .Y (n_30));
  XOR2X1 g4973__7482(.A (rd_ptr[4]), .B (n_22), .Y (n_28));
  NAND2BX2 g4977__4733(.AN (empty), .B (rd_en), .Y (n_93));
  XOR2X1 g4932__6161(.A (wr_ptr[4]), .B (n_25), .Y (n_26));
  NAND2BX1 g4979__9315(.AN (full), .B (wr_en), .Y (n_33));
  AOI21XL g4983__9945(.A0 (n_32), .A1 (n_19), .B0 (n_22), .Y (n_23));
  AND2X6 g4980__2883(.A (n_3), .B (n_21), .Y (empty));
  ADDHXL g4967__1666(.A (wr_ptr[3]), .B (n_15), .CO (n_25), .S (n_20));
  NOR2XL g4985__7410(.A (n_32), .B (n_19), .Y (n_22));
  OAI221X1 g4987__6417(.A0 (n_31), .A1 (n_40), .B0 (n_8), .B1
       (rd_ptr[1]), .C0 (n_37), .Y (n_18));
  NOR4X1 g4984__5477(.A (n_10), .B (n_2), .C (n_9), .D (n_11), .Y
       (n_21));
  AOI21XL g4986__2398(.A0 (n_16), .A1 (n_75), .B0 (n_15), .Y (n_17));
  NAND2X1 g4988__5107(.A (n_48), .B (n_73), .Y (n_14));
  NAND2X1 g4990__6260(.A (rd_ptr[1]), .B (n_13), .Y (n_19));
  INVX1 g4982(.A (n_15), .Y (n_12));
  OAI22XL g4989__4319(.A0 (wr_ptr[0]), .A1 (n_0), .B0 (rd_ptr[2]), .B1
       (n_16), .Y (n_11));
  XNOR2X1 g4994__8428(.A (wr_ptr[3]), .B (n_32), .Y (n_10));
  OAI22XL g4995__5526(.A0 (wr_ptr[2]), .A1 (n_8), .B0 (rd_ptr[0]), .B1
       (n_1), .Y (n_9));
  MXI2XL g4996__6783(.A (n_31), .B (rd_ptr[1]), .S0 (rd_ptr[0]), .Y
       (n_7));
  INVX1 g4998(.A (n_42), .Y (n_13));
  INVX1 g5003(.A (n_74), .Y (n_73));
  XNOR2X1 g4993__3680(.A (wr_ptr[1]), .B (n_31), .Y (n_2));
  INVX1 g5005(.A (n_48), .Y (n_50));
  NOR2XL g4991__1617(.A (n_16), .B (n_75), .Y (n_15));
  NOR2XL g5007__2802(.A (wr_ptr[1]), .B (n_1), .Y (n_74));
  OR2X1 g5002__1705(.A (n_0), .B (n_8), .Y (n_42));
  OR2X1 g5008__5122(.A (rd_ptr[0]), .B (n_8), .Y (n_37));
  XNOR2X1 g4997__8246(.A (rd_ptr[4]), .B (wr_ptr[4]), .Y (n_3));
  NAND2X1 g5009__7098(.A (wr_ptr[1]), .B (n_1), .Y (n_48));
  OR2X1 g5010__6131(.A (rd_ptr[2]), .B (n_0), .Y (n_40));
  NOR2XL g4999__1881(.A (rd_ptr[0]), .B (rd_ptr[2]), .Y (n_46));
  NOR2X1 g5000__5115(.A (wr_ptr[1]), .B (wr_ptr[0]), .Y (n_71));
  NAND2X1 g5001__7482(.A (wr_ptr[1]), .B (wr_ptr[0]), .Y (n_75));
  INVX1 g5016(.A (rst), .Y (n_179));
  SDFFRXL \rd_ptr_reg[0] (.RN (n_179), .CK (clk), .D (n_29), .SE
       (rd_ptr[0]), .SI (n_93), .Q (rd_ptr[0]), .QN (n_0));
  SDFFRXL \wr_ptr_reg[0] (.RN (n_179), .CK (clk), .D (n_30), .SE
       (wr_ptr[0]), .SI (n_33), .Q (wr_ptr[0]), .QN (n_1));
  SDFFRXL \rd_ptr_reg[3] (.RN (n_179), .CK (clk), .D (n_23), .SE
       (n_93), .SI (rd_ptr[3]), .Q (rd_ptr[3]), .QN (n_32));
  SDFFRXL \wr_ptr_reg[3] (.RN (n_179), .CK (clk), .D (n_20), .SE
       (n_33), .SI (wr_ptr[3]), .Q (wr_ptr[3]), .QN (n_44));
  SDFFRXL \wr_ptr_reg[2] (.RN (n_179), .CK (clk), .D (n_17), .SE
       (n_33), .SI (wr_ptr[2]), .Q (wr_ptr[2]), .QN (n_16));
  SDFFRXL \rd_ptr_reg[2] (.RN (n_179), .CK (clk), .D (n_18), .SE
       (n_93), .SI (rd_ptr[2]), .Q (rd_ptr[2]), .QN (n_8));
  SDFFRX2 \rd_ptr_reg[1] (.RN (n_179), .CK (clk), .D (n_7), .SE (n_93),
       .SI (rd_ptr[1]), .Q (rd_ptr[1]), .QN (n_31));
  NOR2BX1 g2(.AN (n_46), .B (n_41), .Y (n_184));
  NOR2BX1 g5179(.AN (n_46), .B (n_39), .Y (n_185));
  NOR2BX1 g5180(.AN (n_46), .B (n_38), .Y (n_186));
  NOR2BX1 g5181(.AN (n_43), .B (n_37), .Y (n_187));
  NOR2BX1 g5182(.AN (n_43), .B (n_40), .Y (n_188));
  NOR2BX4 g5183(.AN (n_21), .B (n_3), .Y (full));
endmodule

